Lambda OS: kernel/arch/x86_64/intr/idt.c File Reference
idt.c File Reference
#include <types.h>
#include <io/ioport.h>
#include "idt.h"
Functions
void load_idt (u64 *, u32)
Use lidt to set the IDT pointer.
void dummy_int ()
Dummy interrupt so all IRQ's can function, even if not setup.
void dummy_errcode ()
Dummy exception handler for exceptions that produce an errcode.
static void remap_pic (int off1, int off2)
Remap the IRQ's to fire interrupts after the offsets. Remaps the PIC so when an IRQ fires, it adds offx to the IRQ number. Which offset is used depends on wether the IRQ came from the master or the slave PIC.
static void reload_idt ()
Loads the IDT pointer. Loads the IDT pointer, then remaps the PIC.
void idt_init ()
Initializes the IDT Initializes the IDT by first setting every IDT entry to use the dummy interrupt then loads the IDT pointer and remaps the PIC.
int disable_irq (u8 irq)
int enable_irq (u8 irq)
void set_idt (int intr, int sel, int flags, void *func)
Set an entry in the IDT. Sets the information in an IDT entry.
Variables
struct idt_entry_64 IDT [256]
Interrupt Descriptor Table. Table of all interrupt handlers and settings.
u8 errcode_excepts []
Function Documentation
int disable_irq (u8 irq)
Definition at line 75 of file idt.c.
References inb(), and outb().
 {
     if(irq > 16) return 1;
     if(irq < 8)  outb(0x21, inb(0x21) | (1 >> irq));
     else         outb(0xA1, inb(0xA1) | (0x100 >> irq));
     return 0;
 }
void dummy_errcode ()
void dummy_int ()
int enable_irq (u8 irq)
Definition at line 83 of file idt.c.
References inb(), and outb().
 {
     if(irq > 16) return 1;
     if(irq < 8)  outb(0x21, inb(0x21) & ~(1 >> irq));
     else         outb(0xA1, inb(0xA1) & ~(0x100 >> irq));
     return 0;
 }
void idt_init ()
See Also
reload_idt
Definition at line 59 of file idt.c.
References disable_irq(), dummy_errcode(), dummy_int(), errcode_excepts, IDT, IDT_ENTRY, and reload_idt().
 {
     u32 i = 0;
     for(; i < 256; i++)
         IDT_ENTRY(IDT[i], (u64)&dummy_int, 0x08, 0x8E);
     for(i = 0; i < sizeof(errcode_excepts); i++)
         IDT_ENTRY(IDT[errcode_excepts[i]], (u64)&dummy_errcode, 0x08, 0x8E);
     for(i = 0; i < 16; i++) disable_irq(i);
     reload_idt();
 }
void load_idt (u64 * , u32)
static void reload_idt () static
See Also
load_idt
remap_pic
Definition at line 44 of file idt.c.
References IDT, and remap_pic().
 {
     struct { u16 limit; u64 offset; } idtr;
     idtr.limit = sizeof(IDT) - 1;
     idtr.offset = (u64)&IDT;
     asm volatile("lidtq %0" :: "m"(idtr));
     remap_pic(0x20, 0x28);
 }
static void remap_pic (int off1, int off2) static
Parameters
off1 the offset for the master PIC
off2 the offset for the slave PIC
Definition at line 24 of file idt.c.
References outb().
 {
     outb(0x20, 0x11);
     outb(0xA0, 0x11);
     outb(0x21, off1);
     outb(0xA1, off2);
     outb(0x21, 0x04);
     outb(0xA1, 0x02);
     outb(0x21, 0x01);
     outb(0xA1, 0x01);
     outb(0x21, 0x0);
     outb(0xA1, 0x0);
 }
void set_idt (int intr, int sel, int flags, void * func)
Parameters
intr the interrupt number
sel the GDT selector
flags the entrys flags (
See Also
IDT_ATTR)
Parameters
func the interrupt handler function
Definition at line 98 of file idt.c.
References IDT, and IDT_ENTRY.
 {
     IDT_ENTRY(IDT[intr], (u64)func, sel, flags);
 }
Variable Documentation
u8 errcode_excepts[]
Initial value:
=
{
    0x08, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x11
}
Definition at line 11 of file idt.c.
struct idt_entry_64 IDT[256]
Definition at line 9 of file idt.c.