Lambda OS: kernel/arch/x86_64/io/serial.c File Reference
serial.c File Reference
#include <types.h>
#include <io/ioport.h>
Functions
void serial_init (u16 port)
Initialize the serial port. Initialize the serial port.
int serial_received (u16 port)
Check if a byte is waiting to be read. Check if a byte is waiting to be read.
char serial_read (u16 port)
Reads a byte from the serial port. Reads a byte from the specified serial port.
int is_transmit_empty (u16 port)
Checks if it is okay to send a byte to the serial port. Checks if it is okay to send a byte to the specified serial port.
void serial_write (u16 port, char a)
Writes a byte to a serial port. Writes a byte to the specified serial port.
Function Documentation
int is_transmit_empty (u16 port)
Parameters
port serial port to check
Definition at line 48 of file serial.c.
References inb().
 {
     return inb(port + 5) & 0x20;
 }
void serial_init (u16 port)
Parameters
port which port to initialize
Definition at line 9 of file serial.c.
References outb().
 {
     outb(port + 1, 0x00);
     outb(port + 3, 0x80);
     outb(port + 0, 0x03);
     outb(port + 1, 0x00);
     outb(port + 3, 0x03);
     outb(port + 2, 0xC7);
     outb(port + 4, 0x0B);
 }
char serial_read (u16 port)
Parameters
port serial port to read from
See Also
serial_received
Definition at line 36 of file serial.c.
References inb(), and serial_received().
 {
     while (serial_received(port) == 0);
     return inb(port);
 }
int serial_received (u16 port)
Parameters
port serial port to check
Definition at line 25 of file serial.c.
References inb().
 {
     return inb(port + 5) & 1;
 }
void serial_write (u16 port, char a)
Parameters
port the serial port to write to
a the byte to write to the port
See Also
is_transmit_empty
Definition at line 60 of file serial.c.
References is_transmit_empty(), and outb().
 {
     while (is_transmit_empty(port) == 0);
     outb(port, a);
 }