Lambda OS: kernel/arch/x86/mm/alloc.h File Reference
alloc.h File Reference
#include <types.h>
#include "paging.h"
Data Structures
struct alcent
< Describes a block of memory
Macros
#define N_ALLOCS 1024
Functions
void * kmalloc (u32 sz)
void kfree (void *ptr)
void init_alloc (u32 base, u32 size)
Macro Definition Documentation
#define N_ALLOCS 1024
Definition at line 4 of file alloc.h.
Function Documentation
void init_alloc (u32 base, u32 size)
Initialize allocation functions.
Parameters
base location of usable memory
size size of usable memory
Initialize allocation functions
Parameters
base base of the usable memory
size amount of usable memory
Definition at line 166 of file alloc.c.
References add_alloc(), alloc_lock, lock(), unlock(), and alcent::valid.
 {
     lock(&alloc_lock);
     struct alcent ae = { .valid = 1, .used = 0, .addr = base, .size = size };
     // Add a free allocation block encompasing all the usable memory
     add_alloc(&ae);
     unlock(&alloc_lock);
 }
void kfree (void * ptr)
Free an allocated memory block
Parameters
pointer to previously allocated memory block
Free an allocated block of memory
Parameters
ptr pointer to the previously allocated memory block
Definition at line 143 of file alloc.c.
References addr, alloc_lock, allocs, ERR_DETAIL, kerror(), lock(), N_ALLOCS, rm_alloc(), unlock(), and alcent::valid.
 {
     kerror(ERR_DETAIL, "Freeing %08X", ptr);
     lock(&alloc_lock);
     int i = 0;
     // Find the corresponding memory block
     for(; i < N_ALLOCS; i++)
         if(allocs[i].valid) // Is it valid?
             if(allocs[i].addr == (u32)ptr) // Is it the correct block?
                 rm_alloc(i); // Free it!
     unlock(&alloc_lock);
 }
void* kmalloc (u32 sz)
Allocates a block of memory
Parameters
sz size of the required memory block
Returns
pointer to memory block
Allocate a block of memory
Parameters
sz size of the required block
Returns
pointer to block
Definition at line 102 of file alloc.c.
References add_alloc(), alcent::addr, addr, alloc_lock, allocs, ERR_DETAIL, find_hole(), kerror(), lock(), alcent::size, size, unlock(), alcent::used, and alcent::valid.
 {
     kerror(ERR_DETAIL, "Allocating %d bytes of memory", sz);
     // We don't want two processes using the same memory block!
     lock(&alloc_lock);
     // Find the smallest memory block that we can use
     int idx = find_hole(sz);
     // Couldn't find one...
     if(idx < 0) return 0;
     if(allocs[idx].size == sz)
     {
         allocs[idx].used = 1;
         unlock(&alloc_lock);
         kerror(ERR_DETAIL, "  -> %08X W", allocs[idx].addr);
         return (void *)allocs[idx].addr;
     }
     allocs[idx].size -= sz; // We are using part of this block
     struct alcent ae = { .valid = 1, .used = 1, .addr = allocs[idx].addr, .size = sz };
     allocs[idx].addr += sz; // We don't want anything else using the allocated memory
     add_alloc(&ae); // We will just assume this worked, the worst that could happen is we can't `free` it (FIXME)
     // Let other processes allocate memory
     unlock(&alloc_lock);
     kerror(ERR_DETAIL, "  -> %08X P", ae.addr);
     return (void *)ae.addr;
 }