var annotated =
[
    [ "_PCI_CLASSCODETABLE", "struct__PCI__CLASSCODETABLE.html", "struct__PCI__CLASSCODETABLE" ],
    [ "_PCI_DEVTABLE", "struct__PCI__DEVTABLE.html", "struct__PCI__DEVTABLE" ],
    [ "_PCI_VENTABLE", "struct__PCI__VENTABLE.html", "struct__PCI__VENTABLE" ],
    [ "alloc_head", "structalloc__head.html", "structalloc__head" ],
    [ "cbuff", "structcbuff.html", "structcbuff" ],
    [ "kbug_proc_msg", "structkbug__proc__msg.html", "structkbug__proc__msg" ],
    [ "kbug_type_msg", "structkbug__type__msg.html", "structkbug__type__msg" ],
    [ "kproc", "structkproc.html", "structkproc" ],
    [ "kvid_kerror_msg", "structkvid__kerror__msg.html", "structkvid__kerror__msg" ],
    [ "kvid_print_msg", "structkvid__print__msg.html", "structkvid__print__msg" ],
    [ "kvid_type_msg", "structkvid__type__msg.html", "structkvid__type__msg" ],
    [ "multiboot_apm_table_tag", "structmultiboot__apm__table__tag.html", "structmultiboot__apm__table__tag" ],
    [ "multiboot_basic_memory_tag", "structmultiboot__basic__memory__tag.html", "structmultiboot__basic__memory__tag" ],
    [ "multiboot_boot_device_tag", "structmultiboot__boot__device__tag.html", "structmultiboot__boot__device__tag" ],
    [ "multiboot_bootloader_name_tag", "structmultiboot__bootloader__name__tag.html", "structmultiboot__bootloader__name__tag" ],
    [ "multiboot_cmdline_tag", "structmultiboot__cmdline__tag.html", "structmultiboot__cmdline__tag" ],
    [ "multiboot_elf_headers_tag", "structmultiboot__elf__headers__tag.html", "structmultiboot__elf__headers__tag" ],
    [ "multiboot_fb_pal_ent", "structmultiboot__fb__pal__ent.html", "structmultiboot__fb__pal__ent" ],
    [ "multiboot_fb_tag", "structmultiboot__fb__tag.html", "structmultiboot__fb__tag" ],
    [ "multiboot_fb_type_pal", "structmultiboot__fb__type__pal.html", "structmultiboot__fb__type__pal" ],
    [ "multiboot_fb_type_rgb", "structmultiboot__fb__type__rgb.html", "structmultiboot__fb__type__rgb" ],
    [ "multiboot_header_tag", "structmultiboot__header__tag.html", "structmultiboot__header__tag" ],
    [ "multiboot_memory_map_entry", "structmultiboot__memory__map__entry.html", "structmultiboot__memory__map__entry" ],
    [ "multiboot_memory_map_tag", "structmultiboot__memory__map__tag.html", "structmultiboot__memory__map__tag" ],
    [ "multiboot_module_tag", "structmultiboot__module__tag.html", "structmultiboot__module__tag" ],
    [ "multiboot_tag", "structmultiboot__tag.html", "structmultiboot__tag" ],
    [ "multiboot_vbe_tag", "structmultiboot__vbe__tag.html", "structmultiboot__vbe__tag" ],
    [ "pci_device", "structpci__device.html", "structpci__device" ],
    [ "time_block", "structtime__block.html", "structtime__block" ],
    [ "uproc", "structuproc.html", "structuproc" ]
];