Lambda OS: kernel/arch/x86/dev/keyb/input.h File Reference
input.h File Reference
#include <types.h>
Functions
void keyb_init (void)
Function Documentation
void keyb_init (void)
Initializes the keyboard.
Checks that the keyboard is in working condition
Sets the keyboard interrupt handler
Enables the keyboard IRQ
Creates and adds an input device driver entry corresponding to this keyboard
Definition at line 88 of file input.c.
References add_input_dev(), enable_irq(), ERR_MEDERR, IDRIVER_KEYBOARD, inb(), kbd_wait(), kerror(), keyb_int(), KEYBOARD_INT, outb(), and set_interrupt().
 {
     inb(0x60);
     kbd_wait();
     outb(0x60, 0xFF);
     kbd_wait();
     u8 val = 0;
     while((val = inb(0x60)) != 0xAA)
     {
         if(val == 0xFE)
         {
             inb(0x60);
             kbd_wait();
             outb(0x60, 0xFF);
             kbd_wait();
             continue;
         }
         if(val == 0xFC || val == 0xFD)
         {
             kerror(ERR_MEDERR, "Keyboard self-test failed");
             return;
         }
     }
     set_interrupt(KEYBOARD_INT, (void *)&keyb_int);
     enable_irq(1);
     keyb_dev = add_input_dev(IDRIVER_KEYBOARD, "keyb", 0, 0);
     if(!keyb_dev)
     {
         kerror(ERR_MEDERR, "Could not set up keyboard input device");
     }
 }