Lambda OS: kernel/arch/x86/dev/keyb/input.c File Reference
input.c File Reference
#include <proc/ktasks.h>
#include <intr/intr.h>
#include <io/ioport.h>
#include <err/error.h>
#include <io/input.h>
#include <proc/ipc.h>
#include <intr/idt.h>
#include <video.h>
#include "input.h"
Functions
void keyb_int ()
Assembly interrupt handler.
void keyb_handle (u32)
static void process_code (u32 keycode)
static void kbd_wait (void)
void keyb_init ()
Variables
struct input_dev * keyb_dev
Device struct for the keyboard input handler.
Function Documentation
static void kbd_wait (void) inline static
Waits so writing to keyboard I/O ports too fast doesn't cause a problem
Definition at line 74 of file input.c.
 {
     asm("1:   inb   $0x64,%al\n"
         "testb   $0x02,%al\n"
         "jne   1b");
 }
void keyb_handle (u32 keycode)
Takes the scancode from the buffer, and converts it into another code format recognizable by Lambda OS.
TODO: Add more functionality to the driver
Parameters
keycode key code passed in by assembly interrupt handler
Definition at line 55 of file input.c.
References input_event::data, input_id::id::device, input_id::id::driver, EVENT_KEYPRESS, input_dev::id, IDRIVER_KEYBOARD, KINPUT_TASK_SLOT, krng_add_entropy(), ktask_pids, input_event::origin, process_code(), input_id::s, send_message(), and input_event::type.
 {
     // Doesn't do a whole lot... YET...
     process_code(keycode);
     if(ktask_pids[KINPUT_TASK_SLOT]) // Only send the message if the input task has started
     {
         struct input_event iev;
         iev.origin.s.driver = IDRIVER_KEYBOARD;
         iev.origin.s.device = keyb_dev->id.s.device;
         iev.type = EVENT_KEYPRESS;
         iev.data = keycode;
         send_message(ktask_pids[KINPUT_TASK_SLOT], &iev, sizeof(struct input_event));
     }
     krng_add_entropy((u8)keycode);
 }
void keyb_init (void)
Initializes the keyboard.
Checks that the keyboard is in working condition
Sets the keyboard interrupt handler
Enables the keyboard IRQ
Creates and adds an input device driver entry corresponding to this keyboard
Definition at line 88 of file input.c.
References add_input_dev(), enable_irq(), ERR_MEDERR, IDRIVER_KEYBOARD, inb(), kbd_wait(), kerror(), keyb_int(), KEYBOARD_INT, outb(), and set_interrupt().
 {
     inb(0x60);
     kbd_wait();
     outb(0x60, 0xFF);
     kbd_wait();
     u8 val = 0;
     while((val = inb(0x60)) != 0xAA)
     {
         if(val == 0xFE)
         {
             inb(0x60);
             kbd_wait();
             outb(0x60, 0xFF);
             kbd_wait();
             continue;
         }
         if(val == 0xFC || val == 0xFD)
         {
             kerror(ERR_MEDERR, "Keyboard self-test failed");
             return;
         }
     }
     set_interrupt(KEYBOARD_INT, (void *)&keyb_int);
     enable_irq(1);
     keyb_dev = add_input_dev(IDRIVER_KEYBOARD, "keyb", 0, 0);
     if(!keyb_dev)
     {
         kerror(ERR_MEDERR, "Could not set up keyboard input device");
     }
 }
void keyb_int ()
static void process_code (u32 keycode) static
Called every time a keyboard IRQ occurs. Checks to see if shift, ctrl, or alt are pressed or released
Parameters
keycode code that the keyboard has given us
Definition at line 21 of file input.c.
References KEYB_STATE_ALT, KEYB_STATE_CTRL, KEYB_STATE_SHIFT, and input_dev::state.
 {
     switch(keycode)
     {
         case 0x2A:
         case 0x36:  keyb_dev->state |= KEYB_STATE_SHIFT;
                     break;
         case 0xAA:
         case 0xB6:  keyb_dev->state &= (u32)~KEYB_STATE_SHIFT;
                     break;
         case 0x1D:  keyb_dev->state |= KEYB_STATE_CTRL;
                     break;
         case 0x9D:  keyb_dev->state &= (u32)~KEYB_STATE_CTRL;
                     break;
         case 0x38:  keyb_dev->state |= KEYB_STATE_ALT;
                     break;
         case 0xB8:  keyb_dev->state &= (u32)~KEYB_STATE_ALT;
                     break;
     }
 }
Variable Documentation
struct input_dev* keyb_dev
Definition at line 14 of file input.c.