Lambda OS: kernel/src/time/delay.c File Reference
delay.c File Reference
#include <proc/mtask.h>
#include <time/time.h>
#include <intr/int.h>
Functions
static void time_over (int pid)
Tells delay it can return. Called when the time specified by delay has run out. Sets the value in timeup corresponding to the callers pid to 1.
void delay (u64 delay)
Waits for a specified amount of time. Creates a time block to wait for delay clock ticks, then waits until the time has run out.
Variables
u8 timeup [500]
Table of values corresponding to pid's telling if the timer is done yet.
Function Documentation
void delay (u64 delay)
Parameters
delay number of ticks to wait for
Definition at line 26 of file delay.c.
References add_time_block(), BLOCK_DELAY, kproc::blocked, current_pid, interrupt_halt(), kproc::pid, proc_by_pid(), procs, and time_over().
 {
     int pid = current_pid;
     int idx = proc_by_pid(pid);
     add_time_block(&time_over, delay, pid);
     procs[idx].blocked |= BLOCK_DELAY;
     interrupt_halt(); // Halt until multitasking comes in
 }
static void time_over (int pid) static
Parameters
pid the pid of the caller to delay
Definition at line 13 of file delay.c.
References BLOCK_DELAY, kproc::blocked, proc_by_pid(), and procs.
 {
     int idx = proc_by_pid(pid);
     procs[idx].blocked &= (u32)~BLOCK_DELAY;
 }
Variable Documentation
u8 timeup[500]
Definition at line 5 of file delay.c.