Lambda OS: kernel/inc/err/error.h File Reference
error.h File Reference
Enumerations
enum error_level {
ERR_DETAIL, ERR_INFO, ERR_BOOTINFO, ERR_SMERR,
ERR_MEDERR, ERR_LGERR, ERR_HALTING
}
Functions
void kerror (error_level errlvl, char *msg,...)
Prints information about the kernel. Disables interrupts so it will not get interrupted, checks to see if the error level is >= the minimum level, and if so, prints the current clock tick, then prints the error message. Then, if en_int != 0, it enables interrupts again.
Variables
typedef __align
Enumeration Type Documentation
enum error_level
Enumerator
ERR_DETAIL
Just a message containing kernel details.
ERR_INFO
Message containing kernel info.
ERR_BOOTINFO
Message containing information about the kernel's boot process.
ERR_SMERR
A small, easily ignored error.
ERR_MEDERR
A slightly worse error, but can USUALLY be ignored.
ERR_LGERR
Great error, system can continue, but a process may have to be killed.
ERR_HALTING
Kernel cannot continue operation bacause of this error.
Definition at line 4 of file error.h.
 {
     ERR_DETAIL,
     ERR_INFO,
     ERR_BOOTINFO,
     ERR_SMERR,
     ERR_MEDERR,
     ERR_LGERR,
     ERR_HALTING
 } error_level;
Function Documentation
void kerror (error_level errlvl, char * msg, ...)
Parameters
errlvl the severity of the message
msg the format string
... the arguments to go along with the format string
Definition at line 20 of file error.c.
References disable_interrupts(), enable_interrupts(), interrupts_enabled(), kerneltime, kprintf(), kprintv(), kput(), and minlvl.
 {
     int en_int = interrupts_enabled();
     disable_interrupts();
     if(errlvl >= minlvl)
     {
         kprintf("[%X%08X] ", (u32)(kerneltime >> 32), (u32)kerneltime);
         __builtin_va_list varg;
         __builtin_va_start(varg, msg);
         kprintv(msg, varg);
         __builtin_va_end(varg);
         kput('\n');
     }
     if(en_int) enable_interrupts();
 }
Variable Documentation
typedef __align