Lambda OS: kernel/arch/x86/mm/gdt.c File Reference
gdt.c File Reference
#include <types.h>
#include "gdt.h"
Functions
void load_gdt (u64 *, u32)
Sets the GDT pointer with lidt
void seg_reload ()
Reloads the segment registers.
void load_tss ()
Sets the TSS descriptor.
void gdt_init ()
Initialize the GDT Initializes the GDT then the TSS.
Variables
u32 TSS [26] = { 0, }
The Task State Segment.
u64 GDT [6]
The Global Descriptor Table.
Function Documentation
void gdt_init ()
Definition at line 23 of file gdt.c.
References GDT, GDT_ENTRY, load_gdt(), load_tss(), seg_reload(), and TSS.
 {
     GDT[5] = GDT_ENTRY((u32)&TSS, sizeof(TSS), 0x0089); // Or should it be 0x00E9?
     TSS[2] = 0x10;
     load_gdt(GDT, sizeof(GDT));
     seg_reload();
     load_tss();
 }
void load_gdt (u64 * , u32)
void load_tss ()
void seg_reload ()
Variable Documentation
u64 GDT[6]
Initial value:
=
{
    GDT_NULL,
    GDT_CODE_KERN,
    GDT_DATA_KERN,
    GDT_CODE_USER,
    GDT_DATA_USER
}
Definition at line 6 of file gdt.c.
u32 TSS[26] = { 0, }
Definition at line 4 of file gdt.c.