Lambda OS: kernel/inc/mm/gdt.h File Reference
gdt.h File Reference
Macros
#define GDT_ENTRY(base, limit, flags)
#define GDT_NULL GDT_ENTRY(0, 0, 0)
#define GDT_CODE_KERN GDT_ENTRY(0, 0xFFFFFFFF, 0xCF9A)
#define GDT_DATA_KERN GDT_ENTRY(0, 0xFFFFFFFF, 0xCF92)
#define GDT_CODE_USER GDT_ENTRY(0, 0xFFFFFFFF, 0xCFFA)
#define GDT_DATA_USER GDT_ENTRY(0, 0xFFFFFFFF, 0xCFF2)
Functions
void gdt_init ()
Macro Definition Documentation
#define GDT_CODE_KERN GDT_ENTRY(0, 0xFFFFFFFF, 0xCF9A)
Definition at line 12 of file gdt.h.
#define GDT_CODE_USER GDT_ENTRY(0, 0xFFFFFFFF, 0xCFFA)
Definition at line 14 of file gdt.h.
#define GDT_DATA_KERN GDT_ENTRY(0, 0xFFFFFFFF, 0xCF92)
Definition at line 13 of file gdt.h.
#define GDT_DATA_USER GDT_ENTRY(0, 0xFFFFFFFF, 0xCFF2)
Definition at line 15 of file gdt.h.
#define GDT_ENTRY (base, limit, flags)
Value:
((((base)  & 0xff000000ULL) << 32) |  \
    (((flags)  & 0x0000ffffULL) << 40) |  \
    (((limit)  & 0x000f0000ULL) << 32) |  \
    (((base)   & 0x00ffffffULL) << 16) |  \
    ((limit)   & 0x0000ffffULL))
Definition at line 4 of file gdt.h.
#define GDT_NULL GDT_ENTRY(0, 0, 0)
Definition at line 11 of file gdt.h.
Function Documentation
void gdt_init ()
Definition at line 19 of file gdt.c.
References GDT, GDT_ENTRY, load_gdt(), load_tss(), seg_reload(), and TSS.
 {
     GDT[5] = GDT_ENTRY((u32)&TSS, sizeof(TSS), 0x0089); // Or should it be 0x00E9?
     TSS[2] = 0x10;
     load_gdt(GDT, sizeof(GDT));
     seg_reload();
     load_tss();
 }