Lambda OS: kernel/arch/x86/intr/idt.h File Reference
idt.h File Reference
Contains definitions for the IDT.
Macros
#define IDT_ENTRY(off, sel, attr)
Allows for easy creation of an IDT entry. Helps easily create an IDT entry.
#define IDT_ATTR(present, dpl, storeseg, type)
Allows for easy IDT attribute creation. Helps easily create an attribute byte for an entry in the IDT.
Enumerations
enum idt_int_type {
task32 = 0x05, int16 = 0x06, trap16 = 0x07, int32 = 0x0E,
trap32 = 0x0F
}
Different IDT entry types. Usable types for the attribute flag type in the IDT.
Functions
void idt_init (void)
Initializes the IDT Initializes the IDT by first setting every IDT entry to use the dummy interrupt then loads the IDT pointer and remaps the PIC.
void set_idt (u8, int, int, void *)
Set an entry in the IDT. Sets the information in an IDT entry.
int disable_irq (u8 irq)
int enable_irq (u8 irq)
Detailed Description
Contains functions and defenitions that allow for the setup and usage of the IDT and interrupts in general.
Definition in file idt.h.
Macro Definition Documentation
#define IDT_ATTR (present, dpl, storeseg, type)
Value:
(((present & 0x01) << 7) | \
    ((dpl      & 0x03) << 5) |  \
    ((storeseg & 0x01) << 4) |   \
    ((type     & 0x0F) << 0))
Parameters
present is the entry present?
dpl privilege level
storeseg the GDT segment the handler is located in
type the type of interrupt this is
See Also
idt_int_type
Definition at line 46 of file idt.h.
#define IDT_ENTRY (off, sel, attr)
Value:
((((u64)off  & 0xFFFF0000ULL) << 32) | \
     (((u64)attr & 0x000000FFULL) << 40) |  \
     (((u64)sel  & 0x0000FFFFULL) << 16) |   \
     (((u64)off  & 0x0000FFFFULL) << 0))
Parameters
off offset of the handler
sel the GDT selector
attr the IDT entry's attribute byte
Definition at line 18 of file idt.h.
Enumeration Type Documentation
enum idt_int_type
Enumerator
task32
32-bit task gate
int16
16-bit interrupt gate
trap16
16-bit trap gate
int32
32-bit interrupt gate
trap32
32-bit trap gate
Definition at line 28 of file idt.h.
 {
     task32 = 0x05,
     int16  = 0x06,
     trap16 = 0x07,
     int32  = 0x0E,
     trap32 = 0x0F
 };
Function Documentation
int disable_irq (u8 irq)
Disable an IRQ line
Parameters
irq the IRQ to be disabled
Returns
returns 0 if success
Definition at line 88 of file idt.c.
References inb(), and outb().
 {
     if(irq > 16) return 1;
     if(irq < 8)  outb(0x21, inb(0x21) | (1 >> irq));
     else         outb(0xA1, inb(0xA1) | (u8)(0x100 >> irq));
     return 0;
 }
int enable_irq (u8 irq)
Enable an IRQ line
Parameters
irq the IRQ to be enabled
Returns
returns 0 if success
Definition at line 102 of file idt.c.
References inb(), and outb().
 {
     if(irq > 16) return 1;
     if(irq < 8)  outb(0x21, inb(0x21) & ~(1 >> irq));
     else         outb(0xA1, inb(0xA1) & ~(0x100 >> irq));
     return 0;
 }
void idt_init (void)
See Also
reload_idt
Initializes the IDT by first setting every IDT entry to use the dummy interrupt then loads the IDT pointer and remaps the PIC.
See Also
reload_idt
Definition at line 53 of file idt.c.
References dummy_int(), ERR_BOOTINFO, ERR_INFO, IDT, IDT_ENTRY, kerror(), and reload_idt().
 {
     kerror(ERR_BOOTINFO, "      -> Setting dummy interrupt vectors");
     int i = 0;
     for(; i < 256; i++)
     {
         kerror(ERR_INFO, "        -> INT %02X", i);
         IDT[i] = IDT_ENTRY((u32)&dummy_int, 0x08, 0x8E);
     }
     reload_idt();
 }
void set_idt (u8 intr, int sel, int flags, void * func)
Parameters
intr the interrupt number
sel the GDT selector
flags the entrys flags
func the interrupt handler function
See Also
IDT_ATTR
Sets the information in an IDT entry.
Parameters
intr the interrupt number
sel the GDT selector
flags the entrys flags (
See Also
IDT_ATTR)
Parameters
func the interrupt handler function
Definition at line 74 of file idt.c.
References IDT, and IDT_ENTRY.
 {
     IDT[intr] = IDT_ENTRY((u32)func, sel, flags);
 }