Lambda OS: kernel/arch/x86/intr/idt.c File Reference
idt.c File Reference
#include <types.h>
#include <io/ioport.h>
#include "idt.h"
Functions
void load_idt (u64 *, u32)
Use lidt to set the IDT pointer.
void dummy_int ()
Dummy interrupt se all IRQ's can function, even if not setup.
static void remap_pic (u8 off1, u8 off2)
static void reload_idt ()
void idt_init ()
Initializes the IDT Initializes the IDT by first setting every IDT entry to use the dummy interrupt then loads the IDT pointer and remaps the PIC.
void set_idt (u8 intr, int sel, int flags, void *func)
Set an entry in the IDT. Sets the information in an IDT entry.
int disable_irq (u8 irq)
int enable_irq (u8 irq)
Variables
u64 IDT [256]
Interrupt Descriptor Table. Table of all interrupt handlers and settings.
Function Documentation
int disable_irq (u8 irq)
Disable an IRQ line
Parameters
irq the IRQ to be disabled
Returns
returns 0 if success
Definition at line 81 of file idt.c.
References inb(), and outb().
 {
     if(irq > 16) return 1;
     if(irq < 8)  outb(0x21, inb(0x21) | (1 >> irq));
     else         outb(0xA1, inb(0xA1) | (u8)(0x100 >> irq));
     return 0;
 }
void dummy_int ()
int enable_irq (u8 irq)
Enable an IRQ line
Parameters
irq the IRQ to be enabled
Returns
returns 0 if success
Definition at line 95 of file idt.c.
References inb(), and outb().
 {
     if(irq > 16) return 1;
     if(irq < 8)  outb(0x21, inb(0x21) & ~(1 >> irq));
     else         outb(0xA1, inb(0xA1) & ~(0x100 >> irq));
     return 0;
 }
void idt_init (void)
Initializes the IDT by first setting every IDT entry to use the dummy interrupt then loads the IDT pointer and remaps the PIC.
See Also
reload_idt
Definition at line 50 of file idt.c.
References dummy_int(), IDT, IDT_ENTRY, and reload_idt().
 {
     int i = 0;
     for(; i < 256; i++)
         IDT[i] = IDT_ENTRY((u32)&dummy_int, 0x08, 0x8E);
     reload_idt();
 }
void load_idt (u64 * , u32)
static void reload_idt () static
Loads the IDT pointer, then remaps the PIC.
See Also
load_idt
remap_pic
Definition at line 38 of file idt.c.
References IDT, load_idt(), and remap_pic().
 {
     load_idt(IDT, sizeof(IDT)-1);
     remap_pic(0x20, 0x28);
 }
static void remap_pic (u8 off1, u8 off2) static
Remaps the PIC so when an IRQ fires, it adds offx to the IRQ number. Which offset is used depends on wether the IRQ came from the master or the slave PIC.
Parameters
off1 the offset for the master PIC
off2 the offset for the slave PIC
Definition at line 18 of file idt.c.
References outb().
 {
     outb(0x20, 0x11);
     outb(0xA0, 0x11);
     outb(0x21, off1);
     outb(0xA1, off2);
     outb(0x21, 0x04);
     outb(0xA1, 0x02);
     outb(0x21, 0x01);
     outb(0xA1, 0x01);
     outb(0x21, 0x0);
     outb(0xA1, 0x0);
 }
void set_idt (u8 intr, int sel, int flags, void * func)
Sets the information in an IDT entry.
Parameters
intr the interrupt number
sel the GDT selector
flags the entrys flags (
See Also
IDT_ATTR)
Parameters
func the interrupt handler function
Definition at line 67 of file idt.c.
References IDT, and IDT_ENTRY.
 {
     IDT[intr] = IDT_ENTRY((u32)func, sel, flags);
 }
Variable Documentation
u64 IDT[256]
Definition at line 8 of file idt.c.