Lambda OS: kernel/inc/io/input.h File Reference
input.h File Reference
#include <types.h>
Data Structures
union input_id
struct input_id::id
struct input_event
struct input_dev
Macros
#define MAX_INPUT_DEVICES 64
Maximum number of registered input devices.
Enumerations
enum event_type { EVENT_KEYPRESS, EVENT_HWUPDATE, EVENT_MOVEMENT }
enum builtin_idrivers { IDRIVER_KEYBOARD = 0, IDRIVER_MOUSE }
< Input drivers recognized by the kernel
enum keyb_idrv_state { KEYB_STATE_SHIFT = 1, KEYB_STATE_CTRL = 2, KEYB_STATE_ALT = 4, KEYB_STATE_SUPER = 5 }
Functions
struct input_dev * add_input_dev (u16 driver, char *name, u8 name_by_id, u8 id_to_alpha)
struct input_dev * get_idevice (u16 driver, u16 device)
Variables
struct input_dev idevs [MAX_INPUT_DEVICES]
Macro Definition Documentation
#define MAX_INPUT_DEVICES 64
Definition at line 6 of file input.h.
Enumeration Type Documentation
enum builtin_idrivers
Enumerator
IDRIVER_KEYBOARD
Keyboard driver.
IDRIVER_MOUSE
Mouse driver.
Definition at line 25 of file input.h.
 {
     IDRIVER_KEYBOARD = 0,
     IDRIVER_MOUSE
 };
enum event_type
Enumerator
EVENT_KEYPRESS
A key was pressed (ex: keyboard)
EVENT_HWUPDATE
The hardware was updated.
EVENT_MOVEMENT
Something was moved (ex: mouse)
Definition at line 18 of file input.h.
 {
     EVENT_KEYPRESS,
     EVENT_HWUPDATE,
     EVENT_MOVEMENT
 };
enum keyb_idrv_state
Enumerator
KEYB_STATE_SHIFT
KEYB_STATE_CTRL
KEYB_STATE_ALT
KEYB_STATE_SUPER
Definition at line 31 of file input.h.
 {
     KEYB_STATE_SHIFT = 1,
     KEYB_STATE_CTRL  = 2,
     KEYB_STATE_ALT   = 4,
     KEYB_STATE_SUPER = 5
 };
Function Documentation
struct input_dev* add_input_dev (u16 driver, char * name, u8 name_by_id, u8 id_to_alpha)
Adds an input device to input_dev
Parameters
driver the driver that the device will use
name the base name for the driver
name_by_id whether or not to append the device number to the name
id_to_alpha convert device id to a letter, only used if name_by_id == 1
Definition at line 26 of file input.c.
References input_id::id::device, input_id::id::driver, get_next_devid(), input_dev::id, idevs, MAX_INPUT_DEVICES, memcpy(), input_dev::name, input_id::s, input_dev::state, strlen(), and input_dev::valid.
 {
     int i = 0;
     for(; i < MAX_INPUT_DEVICES; i++)
         if(idevs[i].valid == 0) break;
     if(i == MAX_INPUT_DEVICES)
     {
         return 0; // TODO: Produce an error
     }
     idevs[i].id.s.driver = driver;
     idevs[i].id.s.device = get_next_devid(driver);
     idevs[i].state = 0;
     idevs[i].valid = 1;
     memcpy(idevs[i].name, name, strlen(name) + 1);
     if(name_by_id)
     {
         if(id_to_alpha) idevs[i].name[strlen(name)] = (char)idevs[i].id.s.device + 'a';
         else            idevs[i].name[strlen(name)] = (char)idevs[i].id.s.device;
         idevs[i].name[strlen(name) + 1] = 0;
     }
     return &idevs[i];
 }
struct input_dev* get_idevice (u16 driver, u16 device)
Definition at line 55 of file input.c.
References idevs, MAX_INPUT_DEVICES, n, NULL, and input_dev::valid.
 {
     u32 n = (u32)(driver << 16 | device);
     int i = 0;
     for(; i < MAX_INPUT_DEVICES; i++)
         if(idevs[i].valid != 0)
             if(idevs[i].id.n == n)
                 return &idevs[i];
     return NULL;
 }
Variable Documentation
struct input_dev idevs[MAX_INPUT_DEVICES]
Definition at line 4 of file input.c.