Lambda OS: kernel/inc/fs/initrd.h File Reference
initrd.h File Reference
#include <multiboot.h>
#include <types.h>
Data Structures
struct header_old_cpio
Functions
void initrd_init (struct multiboot_header *mboot_head)
void * initrd_find_file (char *name, u32 *size)
Variables
struct header_old_cpio __packed
Function Documentation
void* initrd_find_file (char * name, u32 * size)
Definition at line 110 of file initrd.c.
References header_old_cpio::c_filesize, ERR_SMERR, filedata, filenames, kerror(), n_files, NULL, and strcmp().
 {
     if(!initrd)
     {
         kerror(ERR_SMERR, "initrd file requested without valid initrd");
         return 0;
     }
     int cidx = 0;
     while(cidx <= n_files)
     {
         if(!strcmp(name, filenames[cidx]))
         {
             if(size) *size = files[cidx]->c_filesize;
             return (void *)filedata[cidx];
         }
         cidx++;
     }
     if(size) *size = 0;
     return NULL;
 }
void initrd_init (struct multiboot_header * mboot_head)
Definition at line 24 of file initrd.c.
References header_old_cpio::c_filesize, header_old_cpio::c_magic, header_old_cpio::c_mtime, header_old_cpio::c_namesize, cpio_name, ERR_BOOTINFO, ERR_MEDERR, filedata, filenames, firstframe, multiboot_header::flags, kerror(), map_page(), MBOOT_MODULES, memcpy(), memset(), multiboot_header::mod_addr, multiboot_header::mod_count, mboot_module::mod_end, mboot_module::mod_start, n, n_files, set_frame(), strcmp(), and mboot_module::string.
 {
     kerror(ERR_BOOTINFO, "Loading InitCPIO");
     if(!(mboot_head->flags & MBOOT_MODULES))
     {
         kerror(ERR_BOOTINFO, "  -> No modules to load");
         return;
     }
     struct mboot_module *mod = (struct mboot_module *)mboot_head->mod_addr;
     u32 modcnt = mboot_head->mod_count;
     u32 i = 0;
     while(i < modcnt)
     {
     #if defined(ARCH_X86)
         ptr_t mod_start = (u32)mod->mod_start;
         ptr_t mod_end   = (u32)mod->mod_end;
         u32 b = ((mod_start - (u32)firstframe) / 0x1000);
         for(; b < ((mod_end - (u32)firstframe) / 0x1000) + 1; b++)
         {
             set_frame(b, 1); // Make sure that the module is not overwritten
             map_page((b * 0x1000) + firstframe, (b * 0x1000) + firstframe, 3);
         }
     #endif
         if(!strcmp((char *)mod->string, cpio_name)) initrd = mod;
         i++;
         mod++;
     }
     if(!initrd)
     {
         kerror(ERR_MEDERR, "  -> Could not locate InitCPIO module!");
         return;
     }
     cpio = (struct header_old_cpio *)initrd->mod_start;
     if(cpio->c_magic != 070707)
     {
         kerror(ERR_MEDERR, "  -> Invalid CPIO magic number");
         return;
     }
     struct header_old_cpio *cfile = (struct header_old_cpio *)cpio;
     int cidx = 0;
     while (1)
     {
         if(cfile->c_magic != 0x71C7)
         {
             kerror(ERR_MEDERR, "  -> Invalid or corrupt InitCPIO!\n");
             return;
         }
         files[cidx] = cfile;
         cfile->c_mtime    = n(cfile->c_mtime);
         cfile->c_filesize = n(cfile->c_filesize);
         memcpy(filenames[cidx], (void *)((u32)cfile + sizeof(struct header_old_cpio)), cfile->c_namesize);
         if (!strcmp(filenames[cidx], "TRAILER!!!"))
         {
             memset(&files[cidx], 0, sizeof(struct header_old_cpio));
             return;
         }
         u32 data = ((u32)cfile + sizeof(struct header_old_cpio) + cfile->c_namesize + (cfile->c_namesize & 1));
         filedata[cidx] = data;
         //kerror(ERR_BOOTINFO, "Found %s @ %08x w/ size %d w/ data @ %08x [%d]", filenames[cidx], cfile, files[cidx]->c_filesize, data, files[cidx].c_namesize);
         cfile = (struct header_old_cpio *)(data + cfile->c_filesize + (cfile->c_filesize & 1));
         cidx++;
         n_files++;
     }
 }
Variable Documentation
struct header_old_cpio __packed