Lambda OS: kernel/arch/x86/dev/keyb/input.h File Reference
input.h File Reference
#include <types.h>
Functions
void keyb_init ()
Function Documentation
void keyb_init ()
Definition at line 55 of file input.c.
References enable_irq(), ERR_MEDERR, inb(), kbd_wait(), kerror(), keyb_int(), KEYBOARD_INT, outb(), and set_interrupt().
 {
     inb(0x60);
     kbd_wait();
     outb(0x60, 0xFF);
     kbd_wait();
     u8 val = 0;
     while((val = inb(0x60)) != 0xAA)
     {
         if(val == 0xFE)
         {
             inb(0x60);
             kbd_wait();
             outb(0x60, 0xFF);
             kbd_wait();
             continue;
         }
         if(val == 0xFC || val == 0xFD)
         {
             kerror(ERR_MEDERR, "Keyboard self-test failed");
             return;
         }
     }
     set_interrupt(KEYBOARD_INT, &keyb_int);
     enable_irq(1);
 }