Lambda OS: kernel/arch/x86/dev/keyb/input.c File Reference
input.c File Reference
#include <intr/intr.h>
#include <io/ioport.h>
#include <err/error.h>
#include <intr/idt.h>
#include <video.h>
#include "input.h"
Functions
void keyb_int ()
Assembly interrupt handler.
void keyb_handle (u32 keycode)
static void kbd_wait (void)
void keyb_init ()
Variables
static const char key_table [256]
Corresponds certain keys to certain characters.
static const char key_shift_table [256]
Corresponds certain keys to certain characters, when shift or capslock in enabled.
Function Documentation
static void kbd_wait (void) inline static
Definition at line 48 of file input.c.
 {
     asm("1:   inb   $0x64,%al\n"
         "testb   $0x02,%al\n"
         "jne   1b");
 }
void keyb_handle (u32 keycode)
Takes the scancode from the buffer, and converts it into another code format recognizable by Lambda OS.
TODO: Add more functionality to the driver
Parameters
keycode key code passed in by assembly interrupt handler
Definition at line 40 of file input.c.
References key_table, and kprintf().
 {
     // Doesn't do a whole lot... YET...
     char ch = key_table[keycode];
     if(ch) kprintf("%c", ch);
 }
void keyb_init ()
Definition at line 55 of file input.c.
References enable_irq(), ERR_MEDERR, inb(), kbd_wait(), kerror(), keyb_int(), KEYBOARD_INT, outb(), and set_interrupt().
 {
     inb(0x60);
     kbd_wait();
     outb(0x60, 0xFF);
     kbd_wait();
     u8 val = 0;
     while((val = inb(0x60)) != 0xAA)
     {
         if(val == 0xFE)
         {
             inb(0x60);
             kbd_wait();
             outb(0x60, 0xFF);
             kbd_wait();
             continue;
         }
         if(val == 0xFC || val == 0xFD)
         {
             kerror(ERR_MEDERR, "Keyboard self-test failed");
             return;
         }
     }
     set_interrupt(KEYBOARD_INT, &keyb_int);
     enable_irq(1);
 }
void keyb_int ()
Variable Documentation
const char key_shift_table[256] static
Initial value:
=
{
      0, 0x1B, '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '+', '\b', '\t',
     'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', '{', '}', '\n', 0,   'A',  'S',
     'D', 'F', 'G', 'H', 'J', 'K', 'L', ':', '"', '~',  0,  '|', 'Z', 'X',  'C',  'V',
     'B', 'N', 'M', '<', '>', '?',  0,   0,   0,  ' ',  0,   0,   0,   0,    0,    0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,    0,    0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
}
Definition at line 21 of file input.c.
const char key_table[256] static
Initial value:
=
{
      0 ,0x1B, '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', '\b', '\t',
     'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', '[', ']', '\n', 0,   'a',  's',
     'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', '\'','`',  0 ,'\\', 'z', 'x',  'c',  'v',
     'b', 'n', 'm', ',', '.', '/',  0,   0,   0,  ' ',  0,   0,   0,   0,    0,    0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 ,  0,    0,    0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
}
Definition at line 10 of file input.c.