Lambda OS: kernel/src/intr/interrupts.c File Reference
interrupts.c File Reference
#include <types.h>
#include <err/error.h>
Functions
void interrupts_init ()
Initializes interrupts. Initializes based on the target architecture.
void set_interrupt (u32 n, void *handler)
Attaches an interrupt handler to an interrupt. Attaches an interrupt handler to the specified interrupt.
void timer_init (u32 quantum)
Initializes the system timer. Initializes the timer used by the target architecture.
Function Documentation
void interrupts_init ()
Definition at line 22 of file interrupts.c.
References ERR_BOOTINFO, idt_init(), and kerror().
 {
 #if  defined(ARCH_X86)
     idt_init();
     exceptions_init();
 #elif defined(ARCH_X86_64)
     idt_init();
 #endif
     kerror(ERR_BOOTINFO, 1, "Interrupts enabled");
 }
void set_interrupt (u32 n, void * handler)
Parameters
n number of the interrupt
handler the location of the interrupt handler
Definition at line 39 of file interrupts.c.
References ERR_INFO, kerror(), and set_idt().
 {
 #if   defined(ARCH_X86)
     set_idt(n, 0x08, 0x8E, handler);
 #elif defined(ARCH_X86_64)
     set_idt(n, 0x08, 0x8E, handler);
 #endif
     kerror(ERR_INFO, 1, "Interrupt vector 0x%X set");
 }
void timer_init (u32 quantum)
Parameters
quantum the speed in Hz
Definition at line 54 of file interrupts.c.
References ERR_BOOTINFO, kerror(), and pit_init().
 {
 #ifdef ARCH_X86
     pit_init(quantum);
 #else
     (void)quantum;
 #endif
     kerror(ERR_BOOTINFO, 1, "Timer initialized");
 }