Lambda OS: kernel/src/proc/ktask/kbug.c File Reference
kbug.c File Reference
#include <proc/ktasks.h>
#include <time/time.h>
#include <err/error.h>
#include <proc/ipc.h>
#include <video.h>
Functions
static void idebug ()
__noreturn void kbug_task ()
Function Documentation
static void idebug () static
Definition at line 69 of file kbug.c.
References kproc::blocked, kproc::book, delay(), ERR_INFO, kerror(), kprintf(), MAX_PROCESSES, kproc::name, kproc::prio, procs, proc_book::recvd_msgs, and TYPE_VALID.
 {
     kerror(ERR_INFO, "IDEBUG started");
     // TODO: Switch EIP with a more architecture-generic term
     kprintf("\e[41mPID UID GID SENT     RECEIVED BLCK PRIO NAME            \e[0m\n");
     int i = 0;
     for(; i < MAX_PROCESSES; i++)
         if(procs[i].type & TYPE_VALID)
         {
             delay(5);
             kprintf("% 02d % 02d % 02d %8d %8d   %c  %02d  %s\n",
                 procs[i].pid, procs[i].uid, procs[i].gid, procs[i].book.sent_msgs, procs[i].book.recvd_msgs,
                 ((procs[i].blocked != 0) ? 'Y' : 'N'), procs[i].prio, procs[i].name);
         }
     kerror(ERR_INFO, "IDEBUG finished");
 }
__noreturn void kbug_task (void)
Kernel debugger task
Definition at line 14 of file kbug.c.
References current_pid, idebug(), kbug_proc_msg::info, KBUG_CPUINFO, KBUG_IDEBUG, KBUG_MEMINFO, KBUG_PROC_NPROCS, KBUG_PROC_PROCPID, KBUG_PROC_UPROC, KBUG_PROCINFO, KBUG_TASK_SLOT, kproc_to_uproc(), ktask_pids, MAX_PROCESSES, kbug_mem_msg::mem_addr, kbug_mem_msg::mem_len, n, kbug_type_msg::pid, kbug_proc_msg::pid, kproc::pid, proc_by_pid(), procs, recv_message(), send_message(), kbug_type_msg::type, kbug_proc_msg::type, and TYPE_VALID.
 {
     ktask_pids[KBUG_TASK_SLOT] = current_pid;
     for(;;)
     {
         struct kbug_type_msg ktm;
         recv_message(&ktm, sizeof(struct kbug_type_msg));
         switch(ktm.type)
         {
             case KBUG_PROCINFO: {   struct kbug_proc_msg kpm;
                                     recv_message(&kpm, sizeof(struct kbug_proc_msg));
                                     switch(kpm.type)
{
                                         case KBUG_PROC_NPROCS: {    int i = 0;
                                                                     int n = 0;
                                                                     for(; i < MAX_PROCESSES; i++)
                                                                         if(procs[i].type & TYPE_VALID) n++;
                                                                     send_message(ktm.pid, &n, sizeof(int));
                                                                } break;
                                         case KBUG_PROC_PROCPID: {   int pid = procs[kpm.info].pid;
                                                                     send_message(ktm.pid, &pid, sizeof(int));
                                                                 } break;
                                         case KBUG_PROC_UPROC: { struct uproc proc;
                                                                 int idx = proc_by_pid(kpm.pid);
                                                                 kproc_to_uproc(&procs[idx], &proc);
                                                                 send_message(ktm.pid, &proc, sizeof(struct uproc));
                                                               } break;
                                     }
                                 } break;
             case KBUG_CPUINFO: {    // To be implemented
                                } break;
             case KBUG_MEMINFO: {    // TODO: Check that the requesting process is root or a kernel process
                                     struct kbug_mem_msg kmm;
                                     recv_message(&kmm, sizeof(struct kbug_mem_msg));
                                     // TODO: Check that this won't cause a page fault
                                     send_message(ktm.pid, (void *)(ptr_t)kmm.mem_addr, (int)kmm.mem_len);
                                } break;
             case KBUG_IDEBUG: { idebug();
                               } break;
         }
     }
 }