Lambda OS: kernel/inc/proc/ktask/kbug.h File Reference
kbug.h File Reference
#include <types.h>
Data Structures
struct kbug_type_msg
< Message containing type of next message
struct kbug_proc_msg
< Message containing type of process info it requests
struct kbug_mem_msg
< Message containing memory request
struct kbug_type_proc_msg
struct kbug_type_mem_msg
Macros
#define KBUG_IDEBUG_SUCCESS 0x00000DEB
IDEBUG successfully started.
Enumerations
enum kbug_types { KBUG_PROCINFO, KBUG_CPUINFO, KBUG_MEMINFO, KBUG_IDEBUG }
enum kbug_proc_type { KBUG_PROC_NPROCS, KBUG_PROC_PROCPID, KBUG_PROC_UPROC }
Functions
void kbug_task (void)
Macro Definition Documentation
#define KBUG_IDEBUG_SUCCESS 0x00000DEB
Definition at line 6 of file kbug.h.
Enumeration Type Documentation
enum kbug_proc_type
Enumerator
KBUG_PROC_NPROCS
Number of currently running processes.
KBUG_PROC_PROCPID
The PID of the selected process.
KBUG_PROC_UPROC
Request a user version of the task structure.
Definition at line 18 of file kbug.h.
 {
     KBUG_PROC_NPROCS,
     KBUG_PROC_PROCPID,
     KBUG_PROC_UPROC
 };
enum kbug_types
Enumerator
KBUG_PROCINFO
Request info about a process.
KBUG_CPUINFO
Request info about the CPU.
KBUG_MEMINFO
Request info about memory.
KBUG_IDEBUG
Start the interactive debugger.
Definition at line 10 of file kbug.h.
 {
     KBUG_PROCINFO,
     KBUG_CPUINFO,
     KBUG_MEMINFO,
     KBUG_IDEBUG
 };
Function Documentation
void kbug_task (void)
Kernel debugger task
Definition at line 14 of file kbug.c.
References current_pid, idebug(), kbug_proc_msg::info, KBUG_CPUINFO, KBUG_IDEBUG, KBUG_MEMINFO, KBUG_PROC_NPROCS, KBUG_PROC_PROCPID, KBUG_PROC_UPROC, KBUG_PROCINFO, KBUG_TASK_SLOT, kproc_to_uproc(), ktask_pids, MAX_PROCESSES, kbug_mem_msg::mem_addr, kbug_mem_msg::mem_len, n, kbug_type_msg::pid, kbug_proc_msg::pid, kproc::pid, proc_by_pid(), procs, recv_message(), send_message(), kbug_type_msg::type, kbug_proc_msg::type, and TYPE_VALID.
 {
     ktask_pids[KBUG_TASK_SLOT] = current_pid;
     for(;;)
     {
         struct kbug_type_msg ktm;
         recv_message(&ktm, sizeof(struct kbug_type_msg));
         switch(ktm.type)
         {
             case KBUG_PROCINFO: {   struct kbug_proc_msg kpm;
                                     recv_message(&kpm, sizeof(struct kbug_proc_msg));
                                     switch(kpm.type)
{
                                         case KBUG_PROC_NPROCS: {    int i = 0;
                                                                     int n = 0;
                                                                     for(; i < MAX_PROCESSES; i++)
                                                                         if(procs[i].type & TYPE_VALID) n++;
                                                                     send_message(ktm.pid, &n, sizeof(int));
                                                                } break;
                                         case KBUG_PROC_PROCPID: {   int pid = procs[kpm.info].pid;
                                                                     send_message(ktm.pid, &pid, sizeof(int));
                                                                 } break;
                                         case KBUG_PROC_UPROC: { struct uproc proc;
                                                                 int idx = proc_by_pid(kpm.pid);
                                                                 kproc_to_uproc(&procs[idx], &proc);
                                                                 send_message(ktm.pid, &proc, sizeof(struct uproc));
                                                               } break;
                                     }
                                 } break;
             case KBUG_CPUINFO: {    // To be implemented
                                } break;
             case KBUG_MEMINFO: {    // TODO: Check that the requesting process is root or a kernel process
                                     struct kbug_mem_msg kmm;
                                     recv_message(&kmm, sizeof(struct kbug_mem_msg));
                                     // TODO: Check that this won't cause a page fault
                                     send_message(ktm.pid, (void *)(ptr_t)kmm.mem_addr, (int)kmm.mem_len);
                                } break;
             case KBUG_IDEBUG: { idebug();
                               } break;
         }
     }
 }