Lambda OS: kernel/inc/proc/ktask/kinput.h File Reference
kinput.h File Reference
Functions
void kinput_task (void)
Function Documentation
void kinput_task (void)
Definition at line 48 of file kinput.c.
References current_pid, input_event::data, EVENT_KEYPRESS, KBUG_IDEBUG, KBUG_TASK_SLOT, keycode_to_char(), KINPUT_TASK_SLOT, kprintf(), ktask_pids, kbug_type_msg::pid, recv_message(), send_message(), input_event::type, and kbug_type_msg::type.
 {
     ktask_pids[KINPUT_TASK_SLOT] = current_pid;
     for(;;)
     {
         struct input_event iev;
         recv_message(&iev, sizeof(struct input_event));
         if(iev.type == EVENT_KEYPRESS)
         {
             if(iev.data == 0x01) // ESC -> DEBUG for now
             {
                 struct kbug_type_msg ktm;
                 ktm.pid  = current_pid;
                 ktm.type = KBUG_IDEBUG;
                 while(!ktask_pids[KBUG_TASK_SLOT]);
                 send_message(ktask_pids[KBUG_TASK_SLOT], &ktm, sizeof(struct kbug_type_msg));
             }
             else kprintf("%c", keycode_to_char(&iev));
         }
     }
 }