Lambda OS: kernel/inc/proc/ktask/krng.h File Reference
krng.h File Reference
#include <types.h>
Data Structures
struct rng_request
Functions
void krng_task (void)
void krng_add_entropy (u8 ent)
Function Documentation
void krng_add_entropy (u8 ent)
Definition at line 62 of file krng.c.
References glfsr(), put_cbuff(), rot_seed(), and seed.
 {
     u32 entropy = (u32)(ent | ((ent << 8) ^ seed[3]) | ((ent << 16) ^ seed[0]) | ((ent << 24) ^ seed[2]));
     entropy *= (u32)seed[2];
     rot_seed(0, 3, 2, 1);
 #if __has_builtin(__builtin_readcyclecounter) // Add a bit extra
         seed[3] = (int)__builtin_readcyclecounter();
 #endif
     seed[0] = (int)glfsr((u32)seed[0]);
     u32 t = (u32)seed[2];
     seed[2] = (int)glfsr((u32)seed[1]);
     seed[1] = (int)glfsr(t);
     ent = (entropy & 0x03) | (entropy >> 8 & 0x0C) | (entropy >> 16 & 0x30) | (entropy >> 24 & 0xC0); // Shuffle their values about
     put_cbuff(ent, &e_pool);
 }
void krng_task (void)
Kernel (Pseudo-)Random Number Generator (RNG)
Definition at line 22 of file krng.c.
References current_pid, generate_rand_byte(), KRNG_TASK_SLOT, ktask_pids, rng_request::n_bytes, rng_request::pid, recv_message(), and send_message().
 {
     ktask_pids[KRNG_TASK_SLOT] = current_pid;
     for(;;)
     {
         struct rng_request rngr;
         recv_message(&rngr, sizeof(struct rng_request));
         while(rngr.n_bytes)
         {
             u8 byte = generate_rand_byte();
             send_message(rngr.pid, &byte, 1);
         }
     }
 }