Lambda OS: kernel/src/proc/ktask/krng.c File Reference
krng.c File Reference
#include <proc/ktasks.h>
#include <proc/ipc.h>
#include <mm/cbuff.h>
Functions
u8 generate_rand_byte (void)
__noreturn void krng_task ()
static void rot_seed (int a, int b, int c, int d)
static u32 glfsr (u32 n)
void krng_add_entropy (u8 ent)
Variables
static u8 buff [0x1000]
static struct cbuff e_pool = { 0, 0, 0, 0x1000, buff }
static int seed [4] = { 213424, 464854864, 86445648, 21681121 }
Some arbitrary numbers...
Function Documentation
u8 generate_rand_byte (void)
Definition at line 81 of file krng.c.
References get_cbuff(), rot_seed(), and seed.
 {
     rot_seed(2, 1, 3, 0);
     u32 i = 0xFFFF;
     while(i & 0xFFFFFF00) i = (u32)get_cbuff(&e_pool);
     return (u8)i ^ (u8)seed[0] >> (u8)(i & 0x0F);
 }
static u32 glfsr (u32 n) static
A Galois LFSR
Parameters
n input number
Returns
output number
Definition at line 57 of file krng.c.
 {
     return (n >> 1) ^ (-(n & 1) & 0xD0000001);
 }
void krng_add_entropy (u8 ent)
Definition at line 62 of file krng.c.
References glfsr(), put_cbuff(), rot_seed(), and seed.
 {
     u32 entropy = (u32)(ent | ((ent << 8) ^ seed[3]) | ((ent << 16) ^ seed[0]) | ((ent << 24) ^ seed[2]));
     entropy *= (u32)seed[2];
     rot_seed(0, 3, 2, 1);
 #if __has_builtin(__builtin_readcyclecounter) // Add a bit extra
         seed[3] = (int)__builtin_readcyclecounter();
 #endif
     seed[0] = (int)glfsr((u32)seed[0]);
     u32 t = (u32)seed[2];
     seed[2] = (int)glfsr((u32)seed[1]);
     seed[1] = (int)glfsr(t);
     ent = (entropy & 0x03) | (entropy >> 8 & 0x0C) | (entropy >> 16 & 0x30) | (entropy >> 24 & 0xC0); // Shuffle their values about
     put_cbuff(ent, &e_pool);
 }
__noreturn void krng_task (void)
Kernel (Pseudo-)Random Number Generator (RNG)
Definition at line 22 of file krng.c.
References current_pid, generate_rand_byte(), KRNG_TASK_SLOT, ktask_pids, rng_request::n_bytes, rng_request::pid, recv_message(), and send_message().
 {
     ktask_pids[KRNG_TASK_SLOT] = current_pid;
     for(;;)
     {
         struct rng_request rngr;
         recv_message(&rngr, sizeof(struct rng_request));
         while(rngr.n_bytes)
         {
             u8 byte = generate_rand_byte();
             send_message(rngr.pid, &byte, 1);
         }
     }
 }
static void rot_seed (int a, int b, int c, int d) static
Definition at line 39 of file krng.c.
References seed.
 {
     int _a = seed[0];
     int _b = seed[1];
     int _c = seed[2];
     int _d = seed[3];
     seed[a] = _a;
     seed[b] = _b;
     seed[c] = _c;
     seed[d] = _d;
 }
Variable Documentation
u8 buff[0x1000] static
Definition at line 11 of file krng.c.
struct cbuff e_pool = { 0, 0, 0, 0x1000, buff } static
Definition at line 12 of file krng.c.
int seed[4] = { 213424, 464854864, 86445648, 21681121 } static
Definition at line 15 of file krng.c.