Lambda OS: kernel/inc/proc/ktasks.h File Reference
ktasks.h File Reference
#include <proc/mtask.h>
#include <types.h>
Data Structures
struct kvid_type_msg
< A type message to be sent to kvid
struct kvid_print_msg
< A message telling kvid to print a string
struct kvid_kerror_msg
< A message telling kvid to print a kernel message
struct kbug_type_msg
< Message containing type of next message
struct kbug_proc_msg
< Message containing type of process info it requests
Macros
#define IDLE_TASK_SLOT 0
#define KVID_TASK_SLOT 1
#define KBUG_TASK_SLOT 2
#define KTASK_SLOTS 3
Enumerations
enum kvid_types { KVID_PRINT, KVID_KERROR }
enum kbug_types { KBUG_PROCINFO, KBUG_CPUINFO }
enum kbug_proc_type { KBUG_PROC_NPROCS, KBUG_PROC_PROCPID }
Functions
void init_ktasks ()
Variables
int ktask_pids [KTASK_SLOTS]
Macro Definition Documentation
#define IDLE_TASK_SLOT 0
Definition at line 7 of file ktasks.h.
#define KBUG_TASK_SLOT 2
Definition at line 9 of file ktasks.h.
#define KTASK_SLOTS 3
Definition at line 11 of file ktasks.h.
#define KVID_TASK_SLOT 1
Definition at line 8 of file ktasks.h.
Enumeration Type Documentation
enum kbug_proc_type
Enumerator
KBUG_PROC_NPROCS
Number of currently running processes.
KBUG_PROC_PROCPID
The PID of the selected process.
Definition at line 49 of file ktasks.h.
 {
     KBUG_PROC_NPROCS,
     KBUG_PROC_PROCPID
 };
enum kbug_types
Enumerator
KBUG_PROCINFO
Request info about a process.
KBUG_CPUINFO
Request info about the CPU.
Definition at line 43 of file ktasks.h.
 {
     KBUG_PROCINFO,
     KBUG_CPUINFO
 };
enum kvid_types
Enumerator
KVID_PRINT
Print a message to the screen.
KVID_KERROR
Print information to the screen.
Definition at line 16 of file ktasks.h.
 {
     KVID_PRINT,
     KVID_KERROR
 };
Function Documentation
void init_ktasks ()
Definition at line 90 of file ktasks.c.
References add_kernel_task(), ERR_BOOTINFO, idle_task(), kbug_task(), kerror(), and kvid_task().
 {
     kerror(ERR_BOOTINFO, "Starting kernel tasks");
     kerror(ERR_BOOTINFO, "Starting kernel idle task");
     add_kernel_task(&idle_task, "_idle_", 0x100);
     kerror(ERR_BOOTINFO, "Starting kernel video task");
     add_kernel_task(&kvid_task, "kvid", 0x1000);
 #ifdef DEBUGGER
     kerror(ERR_BOOTINFO, "Starting kernel debug task");
     add_kernel_task(&kbug_task, "kbug", 0x2000);
 #endif // DEBUGGER
 }
Variable Documentation
int ktask_pids[KTASK_SLOTS]
Definition at line 13 of file ktasks.h.