Lambda OS: kernel/src/proc/ktask/ktasks.c File Reference
ktasks.c File Reference
#include <proc/ktasks.h>
#include <err/error.h>
#include <time/time.h>
#include <proc/ipc.h>
#include <intr/int.h>
#include <video.h>
Functions
int get_ktask (int n, u64 time)
void init_ktasks ()
Variables
int ktask_pids [KTASK_SLOTS]
PID's of these tasks.
Function Documentation
int get_ktask (int n, u64 time)
Get a kernel task PID
Parameters
n kernel task number
time max number of clock ticks to wait (0 = infinite)
Definition at line 16 of file ktasks.c.
References busy_wait(), ERR_MEDERR, kerneltime, kerror(), ktask_pids, KTASK_SLOTS, and n.
 {
     if(n >= KTASK_SLOTS)
     {
         kerror(ERR_MEDERR, "Kernel requested pid of invalid ktask: %d", n);
         return 0;
     }
     u64 end = kerneltime + time;
     while((kerneltime < end) || (time == 0))
     {
         if(ktask_pids[n]) return ktask_pids[n];
         busy_wait();
     }
     kerror(ERR_MEDERR, "Could not get pid of ktask %d within %d ticks", n, time);
     return 0;
 }
void init_ktasks (void)
Definition at line 34 of file ktasks.c.
References add_kernel_task(), ERR_BOOTINFO, idle_task(), kbug_task(), kerror(), kinput_task(), krng_task(), kvid_task(), PRIO_DRIVER, PRIO_IDLE, and PRIO_KERNEL.
 {
     kerror(ERR_BOOTINFO, "Starting kernel idle task");
     add_kernel_task((void *)&idle_task, "_idle_", 0x100, PRIO_IDLE);
     kerror(ERR_BOOTINFO, "Starting kernel video task");
     add_kernel_task((void *)&kvid_task, "kvid", 0x1000, PRIO_DRIVER);
 #ifdef DEBUGGER
     kerror(ERR_BOOTINFO, "Starting kernel debug task");
     add_kernel_task((void *)&kbug_task, "kbug", 0x2000, PRIO_KERNEL);
 #endif // DEBUGGER
     kerror(ERR_BOOTINFO, "Starting kernel input task");
     add_kernel_task((void *)&kinput_task, "kinput", 0x1000, PRIO_DRIVER);
     kerror(ERR_BOOTINFO, "Starting kernel RNG task");
     add_kernel_task((void *)&krng_task, "krng", 0x1000, PRIO_DRIVER);
 }
Variable Documentation
int ktask_pids[KTASK_SLOTS]
Definition at line 8 of file ktasks.c.