Lambda OS: kernel/src/proc/ktask/kvid.c File Reference
kvid.c File Reference
#include <proc/ktasks.h>
#include <err/error.h>
#include <proc/ipc.h>
#include <video.h>
Functions
__noreturn void kvid_task ()
Function Documentation
__noreturn void kvid_task (void)
Handles video I/O
Definition at line 9 of file kvid.c.
References current_pid, kvid_kerror_msg::error_level, kerror(), kprintf(), ktask_pids, KVID_KERROR, KVID_PRINT, KVID_TASK_SLOT, recv_message(), kvid_print_msg::string, kvid_kerror_msg::string, and kvid_type_msg::type.
 {
     ktask_pids[KVID_TASK_SLOT] = current_pid;
     for(;;)
     {
         struct kvid_type_msg ktm;
         recv_message(&ktm, sizeof(struct kvid_type_msg));
         switch(ktm.type)
         {
             case KVID_PRINT: {  struct kvid_print_msg kpm;
                                 recv_message(&kpm, sizeof(struct kvid_print_msg));
                                 kprintf("%s", kpm.string);
                              } break;
             case KVID_KERROR: { struct kvid_kerror_msg kkm;
                                 recv_message(&kkm, sizeof(struct kvid_kerror_msg));
                                 kerror(kkm.error_level, "%s", kkm.string); // Maybe we should check the string and PID or something?
                               } break;
         }
     }
 }