Lambda OS: kernel/src/main/main.c File Reference
main.c File Reference
#include <proc/ktasks.h>
#include <proc/mtask.h>
#include <multiboot.h>
#include <intr/intr.h>
#include <err/panic.h>
#include <err/error.h>
#include <time/time.h>
#include <proc/ipc.h>
#include <mm/mm.h>
#include <video.h>
#include <io/pci.h>
#include <io/serial.h>
#include <dev/keyb/input.h>
Functions
void kernel_task ()
int kmain (struct multiboot_header_tag *mboot_tag, u32 magic)
Main kernel function. Initializes all devices, and sets up environment.
Function Documentation
__noreturn void kernel_task ()
Definition at line 56 of file main.c.
References busy_wait(), current_pid, ERR_BOOTINFO, kbug_proc_msg::info, init_ktasks(), KBUG_PROC_NPROCS, KBUG_PROCINFO, KBUG_TASK_SLOT, kerror(), ktask_pids, KVID_PRINT, KVID_TASK_SLOT, kvid_type_msg::pid, kbug_type_msg::pid, kbug_proc_msg::pid, recv_message(), send_message(), kvid_print_msg::string, kvid_type_msg::type, kbug_type_msg::type, and kbug_proc_msg::type.
 {
     kerror(ERR_BOOTINFO, "Main kernel task started");
     init_ktasks();
     struct kvid_type_msg ktm;
     ktm.pid  = current_pid;
     ktm.type = KVID_PRINT;
     struct kvid_print_msg kpm;
     kpm.string = "Hello, kvid!\n";
     while(!ktask_pids[KVID_TASK_SLOT]) busy_wait(); // Wait for kvid task to start
     send_message(ktask_pids[KVID_TASK_SLOT], &ktm, sizeof(struct kvid_type_msg));
     send_message(ktask_pids[KVID_TASK_SLOT], &kpm, sizeof(struct kvid_print_msg));
 #ifdef DEBUGGER
     struct kbug_type_msg kbtm;
     kbtm.pid  = current_pid;
     kbtm.type = KBUG_PROCINFO;
     struct kbug_proc_msg kbpm;
     kbpm.pid  = 0;
     kbpm.type = KBUG_PROC_NPROCS;
     kbpm.info = 0;
     while(!ktask_pids[KBUG_TASK_SLOT]) busy_wait(); // Wait for kbug task to start
     send_message(ktask_pids[KBUG_TASK_SLOT], &kbtm, sizeof(struct kbug_type_msg));
     send_message(ktask_pids[KBUG_TASK_SLOT], &kbpm, sizeof(struct kbug_proc_msg));
     int nprocs;
     recv_message(&nprocs, sizeof(int));
     kerror(ERR_BOOTINFO, "Kbug reports %d running processes", nprocs);
 #endif
     for(;;) busy_wait();
 }
int kmain (struct multiboot_header_tag * mboot_tag, u32 magic)
Parameters
mboot_ptr pointer to multiboot structure
initial_stack location of the initial stack
Definition at line 26 of file main.c.
References busy_wait(), check_commandline(), ERR_BOOTINFO, init_multitasking(), interrupts_init(), kernel_task(), kerror(), keyb_init(), kpanic(), mm_init(), pci_enumerate(), pci_init(), SERIAL_COM1, serial_init(), and timer_init().
 {
     if(magic != 0x36d76289)
         kpanic("Invalid magic number given by the bootloader: 0x%08X", magic);
     serial_init(SERIAL_COM1);
     check_commandline(mboot_tag);
     mm_init(mboot_tag);
     interrupts_init();
     keyb_init();
     timer_init(500);
     pci_enumerate();
     pci_init();
     init_multitasking(&kernel_task, "kern");
     kerror(ERR_BOOTINFO, "Lambda OS kernel finished initializing");
     for(;;) busy_wait();
     (void)mboot_tag;
 }