Lambda OS: kernel/inc/mm/mm.h File Reference
mm.h File Reference
#include <types.h>
#include <multiboot.h>
Functions
void mm_init (struct multiboot_header *mboot_head)
Initializes memory management. Initializes memory management for the target archetecture.
Function Documentation
void mm_init (struct multiboot_header * mboot_head)
Parameters
mboot_head the multiboot header location
mboot_tag the multiboot header location
Definition at line 16 of file mm.c.
References ERR_BOOTINFO, multiboot_header::flags, kerror(), kpanic(), MBOOT_MEMINFO, multiboot_header::mem_upper, and paging_init().
 {
     kerror(ERR_BOOTINFO, "Initializing memory management");
     if(!mboot_head)
         kpanic("Multiboot header pointer is NULL!");
     if(!mboot_head->flags & MBOOT_MEMINFO)
         kpanic("Multiboot header entries mem_* are not available!");
 #if defined(ARCH_X86)
     kerror(ERR_BOOTINFO, "  -> Paging");
     paging_init(mboot_head->mem_upper * 1024); // memory in mem_tag is in KiB
 #endif
     kerror(ERR_BOOTINFO, "Memory management enabled");
 }