Lambda OS: kernel/src/mm/mm.c File Reference
mm.c File Reference
#include <mm/mm.h>
#include <multiboot.h>
#include <video.h>
#include <err/panic.h>
Functions
void mm_init (struct multiboot_header_tag *mboot_tag)
Initializes memory management. Initializes memory management for the target archetecture.
void * alloc_page ()
Allocate a page. Allocate a page the size of the target architecture's pages and using the target architecture's page allocator. Can later be freed by free_page
void free_page (void *page)
Free an allocated page. Free a page allocated by alloc_page
Function Documentation
void* alloc_page ()
Returns
the location of the page
See Also
free_frame
Definition at line 36 of file mm.c.
References alloc_frame().
 {
 #if   defined(ARCH_X86)
     return alloc_frame();
 #elif defined(ARCH_X86_64)
     return 0;
 #endif
 }
void free_page (void * page)
Parameters
page pointer to the page to free
See Also
alloc_page
Definition at line 51 of file mm.c.
References free_frame().
 {
 #if   defined(ARCH_X86)
     free_frame(page);
 #elif defined(ARCH_X86_64)
     (void)page;
 #endif
 }
void mm_init (struct multiboot_header_tag * mboot_tag)
Parameters
mboot_tag the multiboot header location
Definition at line 16 of file mm.c.
References find_multiboot_table(), gdt_init(), kpanic(), multiboot_basic_memory_tag::mem_upper, and paging_init().
 {
     struct multiboot_basic_memory_tag *mem_tag = (struct multiboot_basic_memory_tag *)find_multiboot_table(mboot_tag, 4);
     if(!mem_tag)
         kpanic("No memory information tag found in multiboot tags!");
 #if defined(ARCH_X86)
     gdt_init();
     paging_init(mem_tag->mem_upper * 1024); // memory in mem_tag is in KiB
 #endif
 }