Lambda OS: kernel/inc/proc/mtask.h File Reference
mtask.h File Reference
#include <types.h>
#include <proc/proc.h>
Macros
#define STACK_SIZE 0x8000
Size of user stack or if kernel task has a unspecified stack size.
Functions
void * get_eip ()
Get the EIP value of the instruction after the call to this function.
void init_multitasking (void *process, char *name)
void do_task_switch ()
void add_kernel_task (void *process, char *name, u32 stack_size)
int proc_by_pid (int pid)
void exit (int code)
Variables
struct kproc procs [MAX_PROCESSES]
int current_pid
The PID of the currently running process.
int tasking
Whether or not multitasking has been started or not.
Macro Definition Documentation
#define STACK_SIZE 0x8000
Definition at line 25 of file mtask.h.
Function Documentation
void add_kernel_task (void * process, char * name, u32 stack_size)
Definition at line 41 of file mtask.c.
References block_page(), cbuff::buff, kproc::children, cbuff::count, current_pid, disable_interrupts(), enable_interrupts(), ERR_INFO, ERR_MEDERR, get_next_open_proc(), kproc::gid, cbuff::head, interrupts_enabled(), kernel_cr3, kerror(), kmalloc(), kpanic(), MAX_CHILDREN, memcpy(), memset(), kproc::messages, kproc::msg_buff, MSG_BUFF_SIZE, next_kernel_pid, kproc::pid, proc_by_pid(), procs, cbuff::size, STACK_SIZE, strlen(), cbuff::tail, tasking, kproc::type, TYPE_KERNEL, TYPE_RANONCE, TYPE_RUNNABLE, TYPE_VALID, and kproc::uid.
 {
     int ints_en = interrupts_enabled();
     disable_interrupts();
     int parent;
     if(tasking) parent = proc_by_pid(current_pid);
     int p = get_next_open_proc();
     if(p == -1) kpanic("Could not add a kernel process to process list.");
     if(tasking)
     {
         int i = 0;
         for(; i < MAX_CHILDREN; i++)
         {
             if(procs[parent].children[i]) continue;
             procs[parent].children[i] = p;
             break;
         }
         if(i == MAX_CHILDREN) kerror(ERR_MEDERR, "Process %d has run out of child slots", procs[parent].pid);
     }
     memcpy(procs[p].name, name, strlen(name) + 1);
     procs[p].pid  = next_kernel_pid--;
     procs[p].uid  = 0;
     procs[p].gid  = 0;
     procs[p].type = TYPE_RUNNABLE | TYPE_KERNEL | TYPE_VALID | TYPE_RANONCE;
 #if  defined(ARCH_X86)
     procs[p].eip = (u32)process;
     procs[p].cr3 = kernel_cr3;
 #ifdef STACK_PROTECTOR
     procs[p].ebp = (u32)kmalloc((stack_size ? stack_size : STACK_SIZE) + 0x2000);
     memset((void *)procs[p].ebp, 0, (stack_size ? stack_size : STACK_SIZE) + 0x2000);
     procs[p].ebp +=            ((stack_size ? stack_size : STACK_SIZE) + 0x1000);
 #else // STACK_PROTECTOR
     procs[p].ebp = (u32)kmalloc((stack_size ? stack_size : STACK_SIZE));
     memset((void *)procs[p].ebp, 0, (stack_size ? stack_size : STACK_SIZE));
     procs[p].ebp +=            ((stack_size ? stack_size : STACK_SIZE));
 #endif // !STACK_PROTECTOR
     //procs[p].ebp += 0x10; procs[p].ebp &= 0xFFFFFFF0; // Small alignment
     procs[p].esp = procs[p].ebp;
     procs[p].stack_end = procs[p].ebp - STACK_SIZE;
     procs[p].stack_beg = procs[p].ebp;
 #ifdef STACK_PROTECTOR
 // TODO: Fix stack guarding:
     //block_page(procs[p].stack_end - 0x1000); // <-- Problematic line
     block_page(procs[p].stack_beg + 0x1000);
 #endif // STACK_PROTECTOR
 #endif // ARCH_X86
 // Set up message buffer
     procs[p].messages.head  = 0;
     procs[p].messages.tail  = 0;
     procs[p].messages.count = 0;
     procs[p].messages.size  = MSG_BUFF_SIZE;
     procs[p].messages.buff  = procs[p].msg_buff;
     if(ints_en) enable_interrupts();
     kerror(ERR_INFO, "Added process %s as pid %d to slot %d", name, procs[p].pid, p);
 }
void do_task_switch ()
Definition at line 131 of file mtask.c.
References kproc::blocked, c_proc, current_pid, get_eip(), MAX_PROCESSES, kproc::pid, procs, tasking, kproc::type, TYPE_RANONCE, and TYPE_RUNNABLE.
 {
     if(!tasking) return;
 #if  defined(ARCH_X86)
     u32 esp, ebp, eip, cr3;
     asm volatile ("mov %%esp, %0" : "=r" (esp));
     asm volatile ("mov %%ebp, %0" : "=r" (ebp));
     eip = (u32)get_eip();
     if(eip == 0xFFFFFFFF)
     {
         return;
     }
 #endif
     if(procs[c_proc].type & TYPE_RANONCE)
     {
 #if  defined(ARCH_X86)
         procs[c_proc].esp = esp;
         procs[c_proc].ebp = ebp;
         procs[c_proc].eip = eip;
 #endif
     }
     else procs[c_proc].type |= TYPE_RANONCE;
     // Switch to next process here...
     c_proc++;
     while(!(procs[c_proc].type & TYPE_RUNNABLE) || procs[c_proc].blocked)
         { c_proc++; if(c_proc >= MAX_PROCESSES) c_proc = 0; }
     current_pid = procs[c_proc].pid;
 #if  defined(ARCH_X86)
     esp = procs[c_proc].esp;
     ebp = procs[c_proc].ebp;
     eip = procs[c_proc].eip;
     cr3 = procs[c_proc].cr3;
     asm volatile("mov %0, %%ebx\n"
                  "mov %1, %%esp\n"
                  "mov %2, %%ebp\n"
                  "mov %3, %%cr3\n"
                  "mov $0xFFFFFFFF, %%eax\n"
                  "sti\n"
                  "jmp *%%ebx"
                  : : "r" (eip), "r" (esp), "r" (ebp), "r" (cr3)
                  : "%ebx", "%esp", "%eax");
 #endif
 }
void exit (int code)
Definition at line 186 of file mtask.c.
References busy_wait(), current_pid, disable_interrupts(), enable_interrupts(), ERR_MEDERR, kproc::exitcode, kerror(), proc_by_pid(), procs, kproc::type, TYPE_RUNNABLE, and TYPE_ZOMBIE.
 {
     disable_interrupts();
     int p = proc_by_pid(current_pid);
     if(p == -1)
     {
         kerror(ERR_MEDERR, "Could not find process by pid (%d)", current_pid);
         enable_interrupts();
         return;
     }
     procs[p].type &= ~(TYPE_RUNNABLE);
     procs[p].type |= TYPE_ZOMBIE; // It isn't removed unless it's parent inquires on it
     procs[p].exitcode = code;
     enable_interrupts();
     for(;;) busy_wait();
 }
void* get_eip ()
void init_multitasking (void * process, char * name)
Definition at line 114 of file mtask.c.
References add_kernel_task(), current_pid, disable_interrupts(), enable_interrupts(), ERR_BOOTINFO, kerror(), procs, tasking, kproc::type, and TYPE_RANONCE.
 {
     disable_interrupts();
     add_kernel_task(process, name, 0);
     procs[0].type &= ~(TYPE_RANONCE); // Don't save registers right away for the first task
     tasking = 1;
     current_pid = -1;
     kerror(ERR_BOOTINFO, "Multitasking enabled");
     enable_interrupts();
 }
int proc_by_pid (int pid)
Definition at line 20 of file mtask.c.
References MAX_PROCESSES, and procs.
 {
     int i = 0;
     for(; i < MAX_PROCESSES; i++)
         if(procs[i].pid == pid) return i;
     return -1;
 }
Variable Documentation
int current_pid
Definition at line 9 of file mtask.h.
struct kproc procs[MAX_PROCESSES]
Definition at line 7 of file mtask.h.
int tasking
Definition at line 11 of file mtask.h.