Lambda OS: kernel/src/err/panic.c File Reference
panic.c File Reference
#include <types.h>
#include <video.h>
#include <intr/intr.h>
Functions
void kpanic (char *msg,...)
Halts OS after printing error information. Disabled interrupts, prints the provided error message, then halts the computer.
Function Documentation
void kpanic (char * msg, ...)
Parameters
msg format string
... arguments to go along with format string
Definition at line 11 of file panic.c.
References disable_interrupts(), interrupt_halt(), kprintf(), and kprintv().
 {
     ptr_t *varg = (ptr_t *)&msg;
     disable_interrupts();
     kprintf("Kernel panic:\n    ");
     kprintv(msg, ++varg);
     // Print regs here
     interrupt_halt();
 }