Lambda OS: kernel/arch/x86/io/pci.h File Reference
pci.h File Reference
#include <types.h>
Data Structures
struct pci_device
Macros
#define MAX_PCI_DEVICES 64
Functions
void pci_enumerate (void)
void pci_init (void)
Variables
struct pci_device __packed
struct pci_device pci_devices [MAX_PCI_DEVICES]
Structure defining all connected PCI devices.
Macro Definition Documentation
#define MAX_PCI_DEVICES 64
Definition at line 28 of file pci.h.
Function Documentation
void pci_enumerate (void)
Enumerate all PCI devices and functions and store them into pci_devices
Definition at line 71 of file pci.c.
References pci_device::bus, pci_device::class, pci_device::device_id, ERR_BOOTINFO, ERR_DETAIL, ERR_SMERR, pci_device::header_type, pci_device::interrupt, kerror(), pci_device::latency_tmr, MAX_PCI_DEVICES, n_pci_devices, pci_devices, pci_read_config_word(), pci_device::prog_if, pci_device::revision_id, pci_device::slot, pci_device::subclass, and pci_device::vendor_id.
 {
     kerror(ERR_BOOTINFO, "Initializing PCI devices");
     u16 tmp;
     u32 bus = 0;
     u32 slot = 0;
     int devn = 0;
     for(; bus <= 255; bus++)
         for(slot = 0; slot <= 255; slot++)
         {
             tmp = pci_read_config_word(bus, slot, 0, 0x00); // Vendor ID
             if(tmp != 0xFFFF)
             {
                 if(devn >= MAX_PCI_DEVICES)
                 {
                     kerror(ERR_SMERR, "Maximum PCI entries reached");
                     break;
                 }
                 pci_devices[devn].bus  = (u8)bus;
                 pci_devices[devn].slot = (u8)slot;
                 u16 vend   = tmp;
                 u16 dev    = pci_read_config_word(bus, slot, 0, 0x01);
                 u8  headt  = pci_read_config_word(bus, slot, 0, 0x0E) & 0xFF;
                 u8  class  = pci_read_config_word(bus, slot, 0, 0x0A) >> 8;
                 u8  sclass = pci_read_config_word(bus, slot, 0, 0x0A) & 0xFF;
                 u8  progif = pci_read_config_word(bus, slot, 0, 0x08) >> 8;
                 u8  revid  = pci_read_config_word(bus, slot, 0, 0x08) & 0xFF;
                 u8  lattmr = pci_read_config_word(bus, slot, 0, 0x0C) >> 8;
                 u8  intln  = pci_read_config_word(bus, slot, 0, 0x3C) & 0xFF;
                 pci_devices[devn].header_type = headt;
                 pci_devices[devn].device_id   = dev;
                 pci_devices[devn].vendor_id   = vend;
                 pci_devices[devn].class       = class;
                 pci_devices[devn].subclass    = sclass;
                 pci_devices[devn].prog_if     = progif;
                 pci_devices[devn].revision_id = revid;
                 pci_devices[devn].latency_tmr = lattmr;
                 pci_devices[devn].interrupt   = intln;
                 devn++;
                 kerror(ERR_DETAIL, "  %02X:%02X -> V: %04X D: %04X Ht: %02X C: %02X SC: %02X IF: %02X INT: %02X", bus, slot, vend, dev, headt, class, sclass, progif, intln);
                 if(headt & 0x80)
                 {
                     u8 func = 1;
                     for(; func < 8; func++)
                     {
                         tmp = pci_read_config_word(bus, slot, func, 0); // Vendor ID
                         if(tmp != 0xFFFF)
{
                             u16 vend   = tmp;
                             u16 dev    = pci_read_config_word(bus, slot, func, 0x01);
                             u8  headt  = pci_read_config_word(bus, slot, func, 0x0E) & 0xFF;
                             u8  class  = pci_read_config_word(bus, slot, func, 0x0A) >> 8;
                             u8  sclass = pci_read_config_word(bus, slot, func, 0x0A) & 0xFF;
                             u8  progif = pci_read_config_word(bus, slot, func, 0x08) >> 8;
                             u8  revid  = pci_read_config_word(bus, slot, func, 0x08) & 0xFF;
                             u8  lattmr = pci_read_config_word(bus, slot, func, 0x0C) >> 8;
                             u8  intln  = pci_read_config_word(bus, slot, func, 0x3C) & 0xFF;
                             pci_devices[devn].header_type = headt;
                             pci_devices[devn].device_id   = dev;
                             pci_devices[devn].vendor_id   = vend;
                             pci_devices[devn].class       = class;
                             pci_devices[devn].subclass    = sclass;
                             pci_devices[devn].prog_if     = progif;
                             pci_devices[devn].revision_id = revid;
                             pci_devices[devn].latency_tmr = lattmr;
                             pci_devices[devn].interrupt   = intln;
                             devn++;
                             kerror(ERR_DETAIL, "    -> F: %d V: %04X D: %04X Ht: %02X C: %02X SC: %02X IF: %02X INT: %02X", func, vend, dev, headt, class, sclass, progif, intln);
                         }
                     }
                 }
             }
         }
     n_pci_devices = devn;
 }
void pci_init (void)
Initializes the PCI device driver
Definition at line 186 of file pci.c.
References bist_test(), pci_device::bus, pci_device::class_idx, pci_device::dev_idx, pci_device::device_id, _PCI_DEVTABLE::DevId, enable_irq(), ERR_SMERR, pci_device::func, kerror(), n, n_pci_devices, PCI_CLASSCODETABLE_LEN, pci_devices, PCI_DEVTABLE_LEN, pci_interrupt(), pci_read_config_word(), PCI_VENTABLE_LEN, pci_write_config_word(), PciClassCodeTable, PciDevTable, PciVenTable, pci_device::prog_if, set_interrupt(), pci_device::slot, pci_device::subclass, _PCI_CLASSCODETABLE::SubClass, pci_device::vend_idx, and pci_device::vendor_id.
 {
     int i = 0;
     for(; i < n_pci_devices; i++)
     {
         u8 bus  = pci_devices[i].bus;
         u8 slot = pci_devices[i].slot;
         u8 fn   = pci_devices[i].func;
         int bist = bist_test(bus, slot, fn);
         if((bist != 0) && (bist != -1))
             kerror(ERR_SMERR, "BIST for %02X:%02X:%02X returned %01X", bus, slot, fn, bist);
         u16 vend = pci_devices[i].vendor_id;
         u32 n = 0;
         pci_devices[i].vend_idx = -1;
         for(; n < PCI_VENTABLE_LEN; n++)
             if(PciVenTable[n].VenId == vend)
             {
                 pci_devices[i].vend_idx = (int)n;
                 break;
             }
         u16 dev = pci_devices[i].device_id;
         pci_devices[i].dev_idx = -1;
         for(n = 0; n < PCI_DEVTABLE_LEN; n++)
             if((PciDevTable[n].VenId == vend) && (PciDevTable[n].DevId == dev))
             {
                 pci_devices[i].dev_idx = (int)n;
                 break;
             }
         u8 class   = pci_devices[i].class;
         u8 sclass  = pci_devices[i].subclass;
         u8 prog_if = pci_devices[i].prog_if;
         pci_devices[i].class_idx = -1;
         for(n = 0; n < PCI_CLASSCODETABLE_LEN; n++)
             if((PciClassCodeTable[n].BaseClass == class) && (PciClassCodeTable[n].SubClass == sclass) && (PciClassCodeTable[n].ProgIf == prog_if))
             {
                 pci_devices[i].class_idx = (int)n;
                 break;
             }
         if(pci_devices[i].interrupt)
         {
             u16 val = pci_read_config_word(bus, slot, fn, 0x04);
             val &= ~(0x400); // Clear the interrupt disable flag
             pci_write_config_word(bus, slot, fn, 0x04, val);
             set_interrupt(pci_devices[i].interrupt, &pci_interrupt);
             enable_irq(pci_devices[i].interrupt);
         }
     }
 }
Variable Documentation
struct pci_device __packed
struct pci_device pci_devices[MAX_PCI_DEVICES]
Definition at line 11 of file pci.c.