Lambda OS: kernel/arch/x86/intr/pit.h File Reference
pit.h File Reference
#include <types.h>
Functions
void pit_init (u32 freq)
Initialize the PIT. Initialized the PIT using the supplied frequency if possible.
Function Documentation
void pit_init (u32 freq)
Parameters
freq frequency in Hz
Definition at line 44 of file pit.c.
References enable_irq(), get_reload(), outb(), pit_int(), set_interrupt(), and TIMER_INT.
 {
     u32 reload = get_reload(freq);
     outb(0x43, 0x34);
     outb(0x40, (u8)reload);
     outb(0x40, (u8)(reload >> 8));
     set_interrupt(TIMER_INT, &pit_int);
     enable_irq(0);
 }