Lambda OS: kernel/arch/x86/intr/pit.c File Reference
pit.c File Reference
#include "pit.h"
#include <io/ioport.h>
#include "idt.h"
#include <intr/intr.h>
#include <time/time.h>
Functions
void pit_int ()
The PIT interrupt handler.
void pit_handler ()
PIT interrupt handler. The main part of the PIT interrupt handler, called from pit_int().
static __inline u32 get_reload (u32 freq)
Creates a PIT reload value. Creates a PIT reload value from the specified frequency.
void pit_init (u32 freq)
Initialize the PIT. Initialized the PIT using the supplied frequency if possible.
Variables
u64 kernel_time
Number of elapsed ticks since the PIT was initialized.
Function Documentation
static __inline u32 get_reload (u32 freq) static
Parameters
freq frequency in Hz
Definition at line 32 of file pit.c.
 {
     if(freq < 18)      return 0x10000;   // Is the frequency too small?
     if(freq > 1193181) return 0x01;     // Is the frequency too large?
     return (1193180 / freq);           // If not, compute the reload value
 }
void pit_handler ()
See Also
pit_int
Definition at line 16 of file pit.c.
References do_time_block_timeup(), kernel_time, MAX_TIME_BLOCKS, and time_blocks.
 {
     kernel_time++;
     register u32 i = 0;
     for(; i < MAX_TIME_BLOCKS; i++)
         if(time_blocks[i].event)
             if(--time_blocks[i].count == 0x00000000)
                 do_time_block_timeup(i);
 }
void pit_init (u32 freq)
Parameters
freq frequency in Hz
Definition at line 44 of file pit.c.
References enable_irq(), get_reload(), outb(), pit_int(), set_interrupt(), and TIMER_INT.
 {
     u32 reload = get_reload(freq);
     outb(0x43, 0x34);
     outb(0x40, (u8)reload);
     outb(0x40, (u8)(reload >> 8));
     set_interrupt(TIMER_INT, &pit_int);
     enable_irq(0);
 }
void pit_int ()
Variable Documentation
u64 kernel_time
Definition at line 9 of file pit.c.