Lambda OS: kernel/arch/x86/dev/vga/print.c File Reference
print.c File Reference
#include <dev/vga/print.h>
#include <err/error.h>
#include <types.h>
Functions
void vga_clear ()
static void scrollup ()
void ansi_escape (void)
void vga_put (char c)
void vga_print (char *str)
void vga_printnum (u32 n, u32 base)
static int get_dec (char *str, char **out)
static void m_escape ()
Variables
static u8 bkgc = 0x00
Background color to use in vga_put.
static u8 forc = 0x07
Foreground color to use in vga_put.
static int xres = 80
The current width of the VGA screen.
static int yres = 25
The current hight of the VGA screen.
static int xpos = 0
X position of the cursor.
static int ypos = 0
Y position of the cursor.
static u8 * vidmem = (u8 *)0xB8000
Pointer to default VGA memory location.
static char buff [256]
static int is_esc = 0
Whether or not we are in an escape sequence.
static int buff_loc = 0
Where in the ANSI escape buffer we are.
static u8 ansi_to_vga [16]
Convert an ansi color to a VGA color.
Function Documentation
void ansi_escape ()
Handles an ANSI escape code;
Definition at line 255 of file print.c.
References buff, buff_loc, is_esc, and m_escape().
 {
     is_esc = 2;
     switch(buff[buff_loc - 1])
     {
         case 'm':   m_escape();
                     break;
     }
 }
static int get_dec (char * str, char ** out) static
Convert a string of base-10 digits into an integer.
Parameters
str string containing the digits
out optional pointer to end of digits, set by this function
Definition at line 160 of file print.c.
References n.
 {
     int n = 0;
     while(*str >= '0' && *str <= '9')
     {
         n *= 10;
         n += (int)(*str - '0');
         str++;
     }
     if(out) *out = str;
     return n;
 }
static void m_escape () static
Handle a "\e[XXm" escape code
Definition at line 184 of file print.c.
References ansi_to_vga, bkgc, buff, forc, get_dec(), n, and NULL.
 {
     int n = get_dec(buff, NULL);
     switch(n)
     {
         case  0:    bkgc = 0;
                     forc = 7;
                     break;
         case  1:    forc |= 8;
                     break;
         case  2:    forc &= ~8;
                     break;
         case  3:    // En Italic
         case  4:    // En Underline
         case  5:    // En Blink
         case  6:    // En Fast Blink
                     break;
         case  7:    n = forc;
                     forc = bkgc;
                     bkgc = (u8)n;
                     break;
         case  8:    // En Hidden
         case  9:    // En Strike-through
         case 20:    // En Fraktur
                     break;
         case 21:    forc &= ~8;
                     break;
         case 22:    bkgc = 0;
                     forc = 7;
                     break;
         case 23:    // Dis Italic & Fraktur
         case 24:    // Dis Underline
         case 25:    // Dis Blink
         case 26:    // Reserved
                     break;
         case 27:    n = forc;
                     forc = bkgc;
                     bkgc = forc;
                     break;
         case 28:    // Dis Hide
         case 29:    // Dis Strike-through
                     break;
         case 39:    forc = 7;
                     break;
         case 49:    bkgc = 0;
                     break;
         default:    if(n >= 30  && n <= 37)  forc = ansi_to_vga[n - 30];
                     if(n >= 40  && n <= 47)  bkgc = ansi_to_vga[n - 40];
                     if(n >= 90  && n <= 97)  forc = ansi_to_vga[n - 90  + 8];
                     if(n >= 100 && n <= 107) bkgc = ansi_to_vga[n - 100 + 8];
                     break;
     }
 }
static void scrollup () static
Copies all text after the first line to the previous line, then clears the final line.
Definition at line 32 of file print.c.
References vidmem, xres, and yres.
 {
     int i = 0;
     for(; i < (xres * (yres - 1) * 2); i++)
         vidmem[i] = vidmem[i + xres*2];
     for(; i < (xres * (yres) * 2); i++)
         vidmem[i] = 0x00;
 }
void vga_clear (void)
Clears the first plane of VGA memory, effectively clearing all text from the screen.
Definition at line 21 of file print.c.
References vidmem, xres, and yres.
 {
     int i = 0;
     for(; i < xres*yres*2; i++)
         *(vidmem + i) = 0x00;
 }
void vga_print (char * str)
Prints every character in a character array , until it reaches a NULL terminator.
Parameters
str the string to print
See Also
vga_put
Definition at line 114 of file print.c.
References vga_put().
 {
     int i = 0;
     while(str[i] != 0)
         vga_put(str[i++]);
 }
void vga_printnum (u32 n, u32 base)
Prints a number using any base between 2 and 16, inclusive.
Parameters
n number to be printed
base base to use when printing the number
See Also
vga_print
Definition at line 128 of file print.c.
References vga_put().
 {
     char nums[16] = "0123456789ABCDEF";
     char ans[16] = { '0' };
     int i = 0;
     while(n)
     {
         ans[i++] = nums[n % base];
         n /= base;
     }
     if(!i) i = 1;
     for(i--; i >= 0; i--)
         vga_put(ans[i]);
 }
void vga_put (char c)
Checks if character is printable, if so it places it in VGA memory, along with a color byte. If the character is not printable, it deals with it accordingly
Parameters
c the input character
Definition at line 53 of file print.c.
References ansi_escape(), bkgc, buff, buff_loc, forc, is_ansi, is_esc, scrollup(), vidmem, xpos, xres, ypos, and yres.
 {
     if(is_esc)
     {
         if(is_esc == 3)
         {
             if(c == '[') is_esc = 1;
             else
             {
                 is_esc = 0;
                 goto __print;
             }
             return;
         }
         buff[buff_loc++] = c;
         if(is_esc == 2)
         {
             if(c == ';') is_esc = 1;
             else goto __print;
         }
         else if(is_ansi(c))
         {
             ansi_escape();
             return;
         }
         else
             return;
     }
 __print:
     switch(c)
     {
         case 0x00:  return;
         case '\t':  xpos = (xpos + 8) & ~(8);
                     break;
         case '\n':  xpos = 0;
                     ypos++;
                     break;
         case '\e':  is_esc = 3;
                     buff_loc = 0;
                     return;
         default:    *(vidmem + (xpos+ypos*xres)*2)     = (u8)c;
                     *(vidmem + (xpos+ypos*xres)*2 + 1) = (u8)((bkgc << 4) | forc);
                     xpos++;
                     break;
     }
     if(xpos >= xres) { xpos = 0; ypos++; }
     if(ypos >= yres) { ypos = yres - 1; scrollup(); }
 }
Variable Documentation
u8 ansi_to_vga[16] static
Initial value:
=
{
    0, 4,  2,  6,  1, 5,  3,  7,
    8, 12, 10, 14, 9, 13, 11, 15
}
Definition at line 175 of file print.c.
u8 bkgc = 0x00 static
Definition at line 5 of file print.c.
char buff[256] static
Definition at line 42 of file print.c.
int buff_loc = 0 static
Definition at line 44 of file print.c.
u8 forc = 0x07 static
Definition at line 6 of file print.c.
int is_esc = 0 static
Definition at line 43 of file print.c.
u8* vidmem = (u8 *)0xB8000 static
Definition at line 14 of file print.c.
int xpos = 0 static
Definition at line 11 of file print.c.
int xres = 80 static
Definition at line 8 of file print.c.
int ypos = 0 static
Definition at line 12 of file print.c.
int yres = 25 static
Definition at line 9 of file print.c.