Lambda OS: kernel/arch/x86/dev/vga/print.h File Reference
print.h File Reference
Contains functions dealing with printing to the VGA screen.
#include <types.h>
Macros
#define is_ansi(x) ((x == 'A') || (x == 'B') || (x == 'C') || (x == 'D') || (x == 's') || (x == 'u') || (x == 'H') || (x == 'J') || (x == 'K') || (x == 'm'))
Functions
void vga_clear (void)
void vga_put (char c)
void vga_print (char *str)
void vga_printnum (u32 n, u32 base)
Detailed Description
Contains functions that help print to and manage the VGA screen.
Definition in file print.h.
Macro Definition Documentation
#define is_ansi (x) ((x == 'A') || (x == 'B') || (x == 'C') || (x == 'D') || (x == 's') || (x == 'u') || (x == 'H') || (x == 'J') || (x == 'K') || (x == 'm'))
Definition at line 47 of file print.h.
Function Documentation
void vga_clear (void)
Clears the first plane of VGA memory, effectively clearing all text from the screen.
Definition at line 21 of file print.c.
References vidmem, xres, and yres.
 {
     int i = 0;
     for(; i < xres*yres*2; i++)
         *(vidmem + i) = 0x00;
 }
void vga_print (char * str)
Prints every character in a character array , until it reaches a NULL terminator.
Parameters
str the string to print
See Also
vga_put
Definition at line 114 of file print.c.
References vga_put().
 {
     int i = 0;
     while(str[i] != 0)
         vga_put(str[i++]);
 }
void vga_printnum (u32 n, u32 base)
Prints a number using any base between 2 and 16, inclusive.
Parameters
n number to be printed
base base to use when printing the number
See Also
vga_print
Definition at line 128 of file print.c.
References vga_put().
 {
     char nums[16] = "0123456789ABCDEF";
     char ans[16] = { '0' };
     int i = 0;
     while(n)
     {
         ans[i++] = nums[n % base];
         n /= base;
     }
     if(!i) i = 1;
     for(i--; i >= 0; i--)
         vga_put(ans[i]);
 }
void vga_put (char c)
Checks if character is printable, if so it places it in VGA memory, along with a color byte. If the character is not printable, it deals with it accordingly
Parameters
c the input character
Definition at line 53 of file print.c.
References ansi_escape(), bkgc, buff, buff_loc, forc, is_ansi, is_esc, scrollup(), vidmem, xpos, xres, ypos, and yres.
 {
     if(is_esc)
     {
         if(is_esc == 3)
         {
             if(c == '[') is_esc = 1;
             else
             {
                 is_esc = 0;
                 goto __print;
             }
             return;
         }
         buff[buff_loc++] = c;
         if(is_esc == 2)
         {
             if(c == ';') is_esc = 1;
             else goto __print;
         }
         else if(is_ansi(c))
         {
             ansi_escape();
             return;
         }
         else
             return;
     }
 __print:
     switch(c)
     {
         case 0x00:  return;
         case '\t':  xpos = (xpos + 8) & ~(8);
                     break;
         case '\n':  xpos = 0;
                     ypos++;
                     break;
         case '\e':  is_esc = 3;
                     buff_loc = 0;
                     return;
         default:    *(vidmem + (xpos+ypos*xres)*2)     = (u8)c;
                     *(vidmem + (xpos+ypos*xres)*2 + 1) = (u8)((bkgc << 4) | forc);
                     xpos++;
                     break;
     }
     if(xpos >= xres) { xpos = 0; ypos++; }
     if(ypos >= yres) { ypos = yres - 1; scrollup(); }
 }