Lambda OS: kernel/src/time/time.c File Reference
time.c File Reference
#include <time/time.h>
#include <err/error.h>
#include <types.h>
Functions
void rollover (int)
void do_time_block_timeup (u32 n)
Called when count reaches 0. This makes it easier for the timer interrupt to call event(). After calling event() it resets the time_blocks[] entry so another process can use it.
void add_time_block (void(*func)(int), u64 count, int pid)
Adds a time block to time_blocks[]. Finds the first free time_block and sets its values to the ones supplied.
Variables
struct time_block time_blocks [MAX_TIME_BLOCKS] = { [MAX_TIME_BLOCKS-1] = {&rollover, 0xFFFFFFFFFFFFFFFF, 0 } }
Array of timeblocks used by various processes.
u64 kerneltime = 0
Number of elapsed ticks since the PIT was initialized.
Function Documentation
void add_time_block (void(*)(int) func, u64 count, int pid)
Parameters
func the function to call when count reaches 0
count the number of ticks to wait before calling func()
pid the pid of the process that is using this time_block
Definition at line 43 of file time.c.
References time_block::count, count, ERR_SMERR, time_block::event, kerror(), MAX_TIME_BLOCKS, and time_block::pid.
 {
     int i = 0;
     for(; i < MAX_TIME_BLOCKS; i++)
     {
         if(time_blocks[i].event) continue;
         time_blocks[i].event = func;
         time_blocks[i].count = count;
         time_blocks[i].pid   = pid;
         return;
     }
     kerror(ERR_SMERR, "No free time blocks");
 }
void do_time_block_timeup (u32 n)
Parameters
n the entry within time_blocks
See Also
time_blocks
Definition at line 24 of file time.c.
References time_block::count, time_block::event, n, NULL, and time_block::pid.
 {
     int pid = time_blocks[n].pid;
     void (*event)(int) = time_blocks[n].event;
     time_blocks[n].event = NULL;
     time_blocks[n].count = 0;
     time_blocks[n].pid   = 0;
     event(pid);
 }
void rollover (int pid)
Parameters
pid Called when the timer rolls over
Definition at line 11 of file time.c.
References add_time_block(), ERR_LGERR, and kerror().
 {
     kerror(ERR_LGERR, "Kernel time rolled over, a reboot is strongly suggested");
     add_time_block(&rollover, 0xFFFFFFFFFFFFFFFF, pid);
 }
Variable Documentation
u64 kerneltime = 0
Definition at line 9 of file time.c.
struct time_block time_blocks[MAX_TIME_BLOCKS] = { [MAX_TIME_BLOCKS-1] = {&rollover, 0xFFFFFFFFFFFFFFFF, 0 } }
Definition at line 7 of file time.c.