Lambda OS: kernel/inc/time/time.h File Reference
time.h File Reference
#include <types.h>
Data Structures
struct time_block
A structure to help with timing. A structure that helps processes keep time. Every timer tick, count will be decremented by 1. When count reaches 0, event() is called.
Macros
#define MAX_TIME_BLOCKS 64
Maximum number of timer blocks able to be used. We cannot let this get too high, or we will experience slowdown.
Typedefs
typedef s64 time_t
Typedef used when specifying UNIX time (not timer ticks)
Functions
void do_time_block_timeup (u32 n)
Called when count reaches 0. This makes it easier for the timer interrupt to call event(). After calling event() it resets the time_blocks[] entry so another process can use it.
void add_time_block (void(*func)(int), u64 count, int pid)
Adds a time block to time_blocks[]. Finds the first free time_block and sets its values to the ones supplied.
void delay (u64 delay)
Waits for a specified amount of time. Creates a time block to wait for delay clock ticks, then waits until the time has run out.
Variables
u64 kerneltime
Number of elapsed ticks since the PIT was initialized.
struct time_block time_blocks [MAX_TIME_BLOCKS]
Array of timeblocks used by various processes.
Macro Definition Documentation
#define MAX_TIME_BLOCKS 64
Definition at line 27 of file time.h.
Typedef Documentation
typedef s64 time_t
Used when specifying UNIX time (not timer ticks).
It is signed so it can represent time before January 1, 1970
Definition at line 12 of file time.h.
Function Documentation
void add_time_block (void(*)(int) func, u64 count, int pid)
Parameters
func the function to call when count reaches 0
count the number of ticks to wait before calling func()
pid the pid of the process that is using this time_block
Definition at line 43 of file time.c.
References time_block::count, count, ERR_SMERR, time_block::event, kerror(), MAX_TIME_BLOCKS, and time_block::pid.
 {
     int i = 0;
     for(; i < MAX_TIME_BLOCKS; i++)
     {
         if(time_blocks[i].event) continue;
         time_blocks[i].event = func;
         time_blocks[i].count = count;
         time_blocks[i].pid   = pid;
         return;
     }
     kerror(ERR_SMERR, "No free time blocks");
 }
void delay (u64 delay)
Parameters
delay number of ticks to wait for
Definition at line 26 of file delay.c.
References add_time_block(), BLOCK_DELAY, kproc::blocked, current_pid, interrupt_halt(), kproc::pid, proc_by_pid(), procs, and time_over().
 {
     int pid = current_pid;
     int idx = proc_by_pid(pid);
     add_time_block(&time_over, delay, pid);
     procs[idx].blocked |= BLOCK_DELAY;
     interrupt_halt(); // Halt until multitasking comes in
 }
void do_time_block_timeup (u32 n)
Parameters
n the entry within time_blocks
See Also
time_blocks
Definition at line 24 of file time.c.
References time_block::count, time_block::event, n, NULL, and time_block::pid.
 {
     int pid = time_blocks[n].pid;
     void (*event)(int) = time_blocks[n].event;
     time_blocks[n].event = NULL;
     time_blocks[n].count = 0;
     time_blocks[n].pid   = 0;
     event(pid);
 }
Variable Documentation
u64 kerneltime
Definition at line 6 of file time.h.
struct time_block time_blocks[MAX_TIME_BLOCKS]
Definition at line 29 of file time.h.