Lambda OS: kernel/src/io/video.c File Reference
video.c File Reference
#include <video.h>
#include <string.h>
#include <mm/mm.h>
#include <multiboot.h>
Macros
#define va_arg __builtin_va_arg
Functions
void kput (char c)
Prints a single character. Uses the current architecture's put function.
void kwput (int c)
void kprint (char *str)
Prints a string of characters. Uses the current architecture's print function.
void kwprint (u16 *str)
static int print_int (u32 num, u8 base, u8 u, u8 pad, u8 padzero, u8 possign, u8 posspace, u8 _case, char *out)
static int get_dec (const char *str, ptr_t *out)
static int print (char *out, const char *format, __builtin_va_list varg)
int sprintf (char *out, const char *format,...)
Creates a string based on input format string and arguments. Uses print to convert the format string and any number of arguments to an output string.
int kprintf (const char *format,...)
Creates and prints a string based on input format string and arguments. Uses print to convert the format string and any number of arguments to a string then prints that string to the screen.
int kprintv (char *format, __builtin_va_list varg)
Creates and prints a string based on input format string and arguments. Uses print to convert the format string and any number of arguments in varg to a string then prints that string to the screen.
Variables
int output_serial = 0
If 0, write to VGA, else, write to serial port pointed to by output_serial
Macro Definition Documentation
#define va_arg __builtin_va_arg
Definition at line 150 of file video.c.
Function Documentation
static int get_dec (const char * str, ptr_t * out) static
Convert a number in a string into an integer. Used by print to make code cleaner.
Parameters
str input string
out pointer to end of number (generated by this function)
Returns
the number found
See Also
print
Definition at line 135 of file video.c.
References n.
 {
     int n = 0;
     while(*str >= '0' && *str <= '9')
     {
         n *= 10;
         n += (int)(*str - '0');
         str++;
     }
     *out = (ptr_t)str;
     return n;
 }
void kprint (char * str)
Prints a string of characters.
Parameters
str the input string
See Also
kput
Definition at line 45 of file video.c.
References kput().
 {
     while(*str) kput(*str++);
 }
int kprintf (const char * format, ...)
Uses print to convert the format string and any number of arguments to a string then prints that string to the screen.
Parameters
format format string
... argument list
Returns
the number of characters printed
See Also
print
Definition at line 370 of file video.c.
References kprint(), and print().
 {
     __builtin_va_list varg;
     __builtin_va_start(varg, format);
     char temp[1024];
     int i = 0;
     while(i < 1024) temp[i++] = ' ';
     int ret = print(temp, format, varg);
     kprint(temp);
     __builtin_va_end(varg);
     return ret;
 }
int kprintv (char * format, __builtin_va_list varg)
Uses print to convert the format string and any number of arguments in varg to a string then prints that string to the screen.
Parameters
format format string
varg argument list
Returns
the number of characters printed
See Also
print
Definition at line 392 of file video.c.
References kprint(), and print().
 {
     char temp[1024];
     int i = 0;
     while(i < 1024) temp[i++] = ' ';
     int ret = print(temp, format, varg);
     kprint(temp);
     return ret;
 }
void kput (char c)
Prints a single character.
Parameters
c the input character
Definition at line 18 of file video.c.
References output_serial, serial_write(), and vga_put().
 {
 #if defined(ARCH_X86)
     if(output_serial) serial_write((u16)output_serial, c);
     else vga_put(c);
 #endif
 }
void kwprint (u16 * str)
Prints a string of wide characters.
Parameters
str the input string
See Also
kwput
Definition at line 56 of file video.c.
References kwput().
 {
     while(*str) kwput(*str++);
 }
void kwput (int c)
Prints a single wide character.
Parameters
c the input character
Definition at line 31 of file video.c.
References output_serial, serial_write(), and vga_put().
 {
 #if defined(ARCH_X86)
     if(output_serial) serial_write((u16)output_serial, (char)c);
     else vga_put((char)c);
 #endif
 }
static int print (char * out, const char * format, __builtin_va_list varg) static
Takes a format string and a list of arguments as input, and produces a string as output.
Parameters
out the output string
format the format string
varg the list of arguments
Returns
the number of charactern placed in out
Definition at line 160 of file video.c.
References FMT_SPEC, get_dec(), print_int(), size, strlen(), va_arg, wcslen(), and ZERO_ALL_VID.
 {
     u8 is_in_spec = 0;
     s8 size = 0;      // Size of the integer
     u8 width = 0;     // Width of the number at minimum
     u8 precision = 0; // Precision
     u8 showsign = 0;  // Show the sign on positive numbers
     u8 signspace = 0; // Place a space before positive numbers
     u8 leftalign = 0; // Align to the left
     u8 padzeros = 0;  // Use zeros instead of spaces for padding
     int nchars = 0;    // Number of chars printed so far
     ptr_t temp;
     for(; *format != 0; format++)
     {
         if(!is_in_spec)
         {
             if(*format == FMT_SPEC)
             {
                 is_in_spec = 1;
                 continue;
             }
             *out++ = *format;
             nchars++;
             continue;
         }
         switch(*format)
         {
             case FMT_SPEC: is_in_spec = 0;
                            *out++ = FMT_SPEC;
                            nchars++;
                            break;
             case 'l': if(size < 2) size++;
                       break;
             case 'L': size = 1;
                       break;
             case 'h': if(size > -2) size--;
                       break;
             case 'z':
             case 'j':
             case 't': size = 0;
                       break;
             case '+': showsign = 1;
                       break;
             case ' ': signspace = 1;
                       break;
             case '-': leftalign = 1;
                       break;
             case '0': padzeros = 1;
                       break;
             case '1':
             case '2':
             case '3':
             case '4':
             case '5':
             case '6':
             case '7':
             case '8':
             case '9': width = (u8)get_dec(format, &temp);
                       format = (char *)(temp - 1);
                       break;
             case '.': format++;
                       precision = (u8)get_dec(format, &temp);
                       format = (char *)(temp - 1);
                       break;
         // Numbers, strings, etc...
             case 'd':
             case 'i': temp = (ptr_t)va_arg(varg, int);
                       if(size == -1) temp &= 0xFFFF;
                       if(size == -2) temp &= 0xFF;
                       if(size == 2){} // TODO: Handle this!
                       temp = (ptr_t)print_int(temp, 10, 0, width, padzeros, showsign, signspace, 0, out);
                       nchars += temp;
                       out += temp-1;
                       ZERO_ALL_VID();
                       break;
             case 'u': temp = (ptr_t)va_arg(varg, u32);
                       if(size == -1) temp &= 0xFFFF;
                       if(size == -2) temp &= 0xFF;
                       if(size == 2){} // TODO: Handle this!
                       temp = (ptr_t)print_int(temp, 10, 1, width, padzeros, showsign, signspace, 0, out);
                       nchars += temp;
                       out += temp-1;
                       ZERO_ALL_VID();
                       break;
             case 'f':
             case 'F':
             case 'e':
             case 'E':
             case 'g':
             case 'G': (void)va_arg(varg, double);
                       ZERO_ALL_VID();
                       break;
             case 'x':
             case 'X': temp = (ptr_t)va_arg(varg, u32);
                       if(size == -1) temp &= 0xFFFF;
                       if(size == -2) temp &= 0xFF;
                       if(size == 2){} // TODO: Handle this!
                       temp = (ptr_t)print_int(temp, 16, 1, width, padzeros, showsign, signspace, (*format == 'X'), out);
                       nchars += temp;
                       out += temp-1;
                       ZERO_ALL_VID();
                       break;
             case 'o': temp = (ptr_t)va_arg(varg, u32);
                       if(size == -1) temp &= 0xFFFF;
                       if(size == -2) temp &= 0xFF;
                       if(size == 2){} // TODO: Handle this!
                       temp = (ptr_t)print_int(temp, 8, 1, width, padzeros, showsign, signspace, 0, out);
                       nchars += temp;
                       out += temp-1;
                       ZERO_ALL_VID();
                       break;
             case 's': if(size > 0)
                       {
                           temp = (ptr_t)va_arg(varg, s16 *);
                           nchars += wcslen((s16 *)temp);
                           while(*(s16 *)temp) *out++ = (char)*(s16 *)temp++;
                       }
                       else
                       {
                           temp = (ptr_t)va_arg(varg, char *);
                           nchars += strlen((char *)temp);
                           while(*(char *)temp) *out++ = *(char *)temp++;
                       }
                       ZERO_ALL_VID();
                       break;
             case 'c': temp = (ptr_t)va_arg(varg, int);
                       if(size > 0) *out++ = (char)temp;
                       else         *out++ = (char)temp;
                       nchars++;
                       ZERO_ALL_VID();
                       break;
             case 'p': temp = (ptr_t)va_arg(varg, ptr_t);
                       temp = (ptr_t)print_int(temp, 16, 1, width, padzeros, showsign, signspace, 1 /* Should this be upper or lower case? */, out);
                       nchars += temp;
                       out += temp-1;
                       break;
             case 'a':
             case 'A': (void)va_arg(varg, double);
                       ZERO_ALL_VID();
                       break;
             case 'n': (void)va_arg(varg, int);
                       ZERO_ALL_VID();
                       break;
         }
     }
     *(out) = 0;
     // These aren't used yet:
     (void)precision;
     (void)leftalign;
     return nchars;
 }
static int print_int (u32 num, u8 base, u8 u, u8 pad, u8 padzero, u8 possign, u8 posspace, u8 _case, char * out) static
Converts an interger into a string and places the output into out Used by print to make the code cleaner.
Parameters
num the number to print
base the base in which to print the number
u wether the number is unsigned
pad how many characters of padding to give the number
padzero wether or not to pad the number with zeros instead of spaces
possign wether or not to place a positive sign in front of positive numbers
posspace wether or not to place a space in front of positive numbers
_case upper or lowercase (for bases above 10)
out the output string/buffer
Returns
the number of characters that have been put in out
See Also
print
Definition at line 80 of file video.c.
References strlen().
 {
     int onum = (int)num;
     if(onum < 0) if(!u) num = (~num) + 1;
     char *nums;
     if(_case) nums = "0123456789ABCDEF";
     else      nums = "0123456789abcdef";
     char ans[16] = { '0', };
     int i = 0;
     while(num)
     {
         ans[i++] = nums[num % base];
         num /= base;
     }
     if(i == 0) i++;
     if(!u)
     {
         if(onum >= 0)
         {
             if(possign)
             {
                 *out++ = '+';
             }
             else if(posspace)
                 *out++ = ' ';
         }
         else if(onum < 0)
             *out++ = '-';
     }
     int p = pad - i;
     if(p > 0)
     {
         while(p--) *out++ = (padzero ? '0' : ' ');
         while(--i >= 0) *out++ = ans[i];
         return (int)((pad > strlen(ans)) ? pad : strlen(ans)) + ((((possign || posspace) && !u) && onum >= 0) || ((onum < 0) && !u)) + 1;
     }
     else
     {
         while(--i >= 0) *out++ = ans[i];
         return (int)(strlen(ans) + ((((possign || posspace) && !u) && onum >= 0) || ((onum < 0) && !u)));
     }
 }
int sprintf (char * out, const char * format, ...)
Uses print to convert the format string and any number of arguments to an output string.
Parameters
out output string
format format string
... argument list
Returns
the number of characters placed in out
See Also
print
Definition at line 352 of file video.c.
References print().
 {
     __builtin_va_list varg;
     __builtin_va_start(varg, format);
     int ret = print(out, format, varg);
     __builtin_va_end(varg);
     return ret;
 }
Variable Documentation
int output_serial = 0
Definition at line 11 of file video.c.