Lambda OS: kernel/inc/video.h File Reference
video.h File Reference
#include <types.h>
#include <multiboot.h>
Macros
#define FMT_SPEC '%'
Format specifier character.
#define ZERO_ALL_VID()
Functions
void init_video (struct multiboot_header_tag *mboot_tag)
void kput (char c)
Prints a single character. Uses the current architecture's put function.
void kwput (int c)
void kprint (char *str)
Prints a string of characters. Uses the current architecture's print function.
void kwprint (u16 *str)
int sprintf (char *out, const char *format,...)
Creates a string based on input format string and arguments. Uses print to convert the format string and any number of arguments to an output string.
int kprintf (const char *format,...)
Creates and prints a string based on input format string and arguments. Uses print to convert the format string and any number of arguments to a string then prints that string to the screen.
int kprintv (char *format, __builtin_va_list varg)
Creates and prints a string based on input format string and arguments. Uses print to convert the format string and any number of arguments in varg to a string then prints that string to the screen.
Macro Definition Documentation
#define FMT_SPEC '%'
Definition at line 41 of file video.h.
#define ZERO_ALL_VID ()
Value:
do {                \
        is_in_spec = 0; \
        size       = 0; \
        width      = 0; \
        precision  = 0; \
        showsign   = 0; \
        signspace  = 0; \
        leftalign  = 0; \
        padzeros   = 0; \
    } while(0);
Definition at line 44 of file video.h.
Function Documentation
void init_video (struct multiboot_header_tag * mboot_tag)
void kprint (char * str)
Parameters
str the input string
Prints a string of characters.
Parameters
str the input string
See Also
kput
Definition at line 45 of file video.c.
References kput().
 {
     while(*str) kput(*str++);
 }
int kprintf (const char * format, ...)
Parameters
format format string
... argument list
Returns
the number of characters printed
See Also
print
Uses print to convert the format string and any number of arguments to a string then prints that string to the screen.
Parameters
format format string
... argument list
Returns
the number of characters printed
See Also
print
Definition at line 370 of file video.c.
References kprint(), and print().
 {
     __builtin_va_list varg;
     __builtin_va_start(varg, format);
     char temp[1024];
     int i = 0;
     while(i < 1024) temp[i++] = ' ';
     int ret = print(temp, format, varg);
     kprint(temp);
     __builtin_va_end(varg);
     return ret;
 }
int kprintv (char * format, __builtin_va_list varg)
Parameters
format format string
varg argument list
Returns
the number of characters printed
See Also
print
Uses print to convert the format string and any number of arguments in varg to a string then prints that string to the screen.
Parameters
format format string
varg argument list
Returns
the number of characters printed
See Also
print
Definition at line 392 of file video.c.
References kprint(), and print().
 {
     char temp[1024];
     int i = 0;
     while(i < 1024) temp[i++] = ' ';
     int ret = print(temp, format, varg);
     kprint(temp);
     return ret;
 }
void kput (char c)
Parameters
c the input character
Prints a single character.
Parameters
c the input character
Definition at line 18 of file video.c.
References output_serial, serial_write(), and vga_put().
 {
 #if defined(ARCH_X86)
     if(output_serial) serial_write((u16)output_serial, c);
     else vga_put(c);
 #endif
 }
void kwprint (u16 * str)
Prints a string of wide characters.
Parameters
str the input string
See Also
kwput
Definition at line 56 of file video.c.
References kwput().
 {
     while(*str) kwput(*str++);
 }
void kwput (int c)
Prints a single wide character.
Parameters
c the input character
Definition at line 31 of file video.c.
References output_serial, serial_write(), and vga_put().
 {
 #if defined(ARCH_X86)
     if(output_serial) serial_write((u16)output_serial, (char)c);
     else vga_put((char)c);
 #endif
 }
int sprintf (char * out, const char * format, ...)
Parameters
out output string
format format string
... argument list
Returns
the number of characters placed in out
See Also
print
Uses print to convert the format string and any number of arguments to an output string.
Parameters
out output string
format format string
... argument list
Returns
the number of characters placed in out
See Also
print
Definition at line 352 of file video.c.
References print().
 {
     __builtin_va_list varg;
     __builtin_va_start(varg, format);
     int ret = print(out, format, varg);
     __builtin_va_end(varg);
     return ret;
 }