#ifndef ARCH_PLAT_CPU_CORTEX_A9_H
#define ARCH_PLAT_CPU_CORTEX_A9_H

#define MPCORE_PERIPHBASE_OFF_SCU    (0x0000UL)
#define MPCORE_PERIPHBASE_OFF_ICC    (0x0100UL)
#define MPCORE_PERIPHBASE_OFF_GTIMER (0x0200UL)
#define MPCORE_PERIPHBASE_OFF_PTIMER (0x0600UL)
#define MPCORE_PERIPHBASE_OFF_DCU    (0x1000UL)

#endif