#ifndef ARCH_PLAT_HW_VEXPRESS_A9_H
#define ARCH_PLAT_HW_VEXPRESS_A9_H

#include <arch/plat/cpu/cortex_a9.h>

#define VEXPRESSA9_INT_WDOG0 (32)
#define VEXPRESSA9_INT_SWI   (33)
#define VEXPRESSA9_INT_TIM01 (34)
#define VEXPRESSA9_INT_TIM23 (35)
#define VEXPRESSA9_INT_RTC   (36)
#define VEXPRESSA9_INT_UART0 (37)
#define VEXPRESSA9_INT_UART1 (38)
#define VEXPRESSA9_INT_UART2 (39)
#define VEXPRESSA9_INT_UART3 (40)
#define VEXPRESSA9_INT_MCI0  (41)
#define VEXPRESSA9_INT_MCI1  (42)
#define VEXPRESSA9_INT_AACI  (43)
#define VEXPRESSA9_INT_KMI0  (44)
#define VEXPRESSA9_INT_KMI1  (45)
#define VEXPRESSA9_INT_CLCD  (46)
#define VEXPRESSA9_INT_ETH   (47)
#define VEXPRESSA9_INT_USB   (48)
#define VEXPRESSA9_INT_PCIE  (49)

#endif